### ISSUE TITLE
ES5 option is now set per default

### ISSUE THREAD

**Issue by mderrick** [jshint/jshint#1137]
Since 2.0.1 the error "ES5 option is now set per default" shows when using es5: true.

In our development environment we have multiple versions of JSHint being used (npm packages, IDE's and builds) of which not all are maintained by us and therefore can not be updated.

This means you have introduced a breaking change..

This flag should not error in latest versions, but instead, silently ignore it.

Thanks!

**Comment by akauppi** [comment]
Still having this, in 2015. Using various `-Wxxx` flags turns those warnings into these info messages. How do I turn off the info messages, then? 

Only targeting ES5, so this whole thing is a nuisance and I agree with the criticism in this issue. (btw, if this is 'closed', how come the problem is still there with jshint 2.6.3?

**Comment by rwaldron** [comment]
Are you asking that JSHint just ignore the setting when users explicitly set `es5: true`?

**Comment by akauppi** [comment]
I won't repeat @jchorn 's reasoning above - I simply think he is right and I cannot understand the logic that `jshint` currently imposes on me.

I have a project that's ES5 only. Good. I would like to state that in the config file but since that causes a warning, I don't. Acceptable. Then, when I do things s.a. /*jshint -W106 */ among the code, I get such warnings supressed, but a number of "ES5 is now default" info messages arise instead! Alice in the wonderland.

I "solved" this today by simply feeding `jshint` output via `grep` that eats up those info messages, since I wasn't able to find another way. Works. But... Alice in the wonderland...

**Comment by caitp** [comment]
I don't see why we need to warn about it, it is kind of weird

**Comment by guyzmo** [comment]
This was a sensible choice when bumping up to v2.0, in order to warn all codes that the default changed from es3 to es5, and to quote @valueof:

> *This is not the only breaking change introduced in 2.0 (hence the major version bump). What would be worse, in my opinion, is if backwards incompatible changes sneak in quietly. This warning will be removed sometimes soon but for now I think it's good to have it.*

So, two years after, I guess the *sometimes soon* part is pretty ok, as people have been well aware for a long time that default has changed!
