### ISSUE TITLE
Please change jshint.js license, remove bad or evil

### ISSUE THREAD

**Issue by osallou** [jshint/jshint#1234]
Hi,
could you please modify the jshint.js license to be a real MIT license?

The "The Software shall be used for Good, not Evil." prevents library to be packaged in Debian and maybe other repo where code should really be free of use (yes, even evil). And honestly, if someone wants to use it for evil... well I don't think he will care about the license  :-)

Thanks

Olivier

**Comment by piotr1212** [comment]
Thank you very much for working on this issue, I want to get this in Fedora. What exactly still needs to be done?

**Comment by jugglinmike** [comment]
**The best way to confirm that we're still working on this** is to check [my `master-free` branch](https://github.com/jugglinmike/jshint/tree/master-free) -- I certainly wouldn't be keeping that in sync if I didn't intend to use it!

@piotr1212 Currently, we need to confirm the change with some of the previous contributors. It sounds like you're an RPM maintainer--is that correct?

**Comment by piotr1212** [comment]
Thanks you for the update. I'll just wait paintently ;)
And yes, I am a package maintainer for Fedora/EPEL, There are many nodejs modules which depend on jshint and can't be packaged now...

**Comment by paultag** [comment]
I'm with @piotr1212 - this has blocked some tools into Debian that I want to see. let's get this nonfree clause removed!

**Comment by cburgmer** [comment]
I would like to promote this issue and call on all contributors to not forget our government employees inside the NSA or GCHQ that maintain parts of the pervasive surveillance system written in JavaScript. Clean code for everybody!

**Comment by paultag** [comment]
![](http://2.bp.blogspot.com/-eO8o9_rI154/Tw4x1NQg0EI/AAAAAAAAAnk/QeUJsEsqgMg/s1600/gus-psyche-popcorn.gif)

**Comment by foysavas** [comment]
I've signed the CLA and encourage others to do the same.

As a curiosity, I once had and took the opportunity to ask Howard Zinn to define evil. He, however, snapped back at me, claiming that if I didn't know what evil was by my age, then, for sure, I never would. After years of reflection on that statement, Zinn, of course, was right – and to be errantly good has remained the best I can hope for.

**Comment by thejameskyle** [comment]
Is this license going to be updated as well? https://github.com/jshint/jshint/blob/master/src/jshint.js#L19

**Comment by jugglinmike** [comment]
@thejameskyle That is the only license that needs changing. We'll be sure to update it as soon as we can

**Comment by kreynen** [comment]
Just found an older copy of jshint.js that made its way into a Drupal project.  I'm having trouble following this issue.  Is the "God, not Evil" clause being removed?  The activity in https://github.com/webjars/webjars/issues/1127 makes me think that clause will remain.

**Comment by jugglinmike** [comment]
**The best way to confirm that we're still working on this** is to check [my `master-free` branch](https://github.com/jugglinmike/jshint/tree/master-free) -- I certainly wouldn't be keeping that in sync if I didn't intend to use it!

**Comment by kreynen** [comment]
@jugglinmike I read that response the first time you posted it in response to @piotr1212 back in January, but I wasn't sue why someone would be working on getting the AND operator working properly in POM if you were merging this... so I asked. I was really hoping for > update and < snark.  

As part of Drupal's Licensing Working Group, we deal with licensing issues for a community with thousands of projects and contributors.  I understand how frustrating it can be to get these resolved... and how thankless.  

**SO THANK YOU!**  Unenforceable, non-standard licensing clauses like that are incredibly unproductive.  

While I'm guilty of my share of responses like this, you should be aware of how off putting this is for someone who isn't familiar with your project.

Since there is nothing in the branch's README.md, description, an open PR with comments or in this issue indicating what still needs to be done, people are going to continue to periodically ask until this gets merged.  

If you are going to use a boilerplate response to anyone who asks, I'd suggest some changes.  "I didn't intend to use it!" is != "we didn't intend to merge it".   It would be less off putting to say something like...

*If https://github.com/jugglinmike/jshint/tree/master-free is being updated, we are actively working on resolving this.  Limited resources prevent us from posting status updates as often we'd like, but this issue will remain open until the "Good, not Evil" clause is removed.*

This file wasn't essential to the Drupal project so it was removed, but this issue is becoming a great case study in the ripple effect modifying a truly open and vetted license can have.  Let me know if there is anything I can do to help get this resolved.

**Comment by jugglinmike** [comment]
I did not intend to be passive aggressive. I interpreted, "I'm having trouble following this issue" as, "I missed your response among all the other discussion". I appreciate your suggestion for a more complete explanation, and I agree that it is an improvement. I'll follow up with a more visible comment dedicated to that message.

As for the issue you referenced: I think there's value for that project to be robust in its parsing of SPDX regardless of any specific project's current configuration. So it would make sense to resolve that issue generally... to me, anyway!

**Comment by jugglinmike** [comment]
## Checking the Status of this Effort

If https://github.com/jugglinmike/jshint/tree/master-free is being updated, we are actively working on resolving this. Limited resources prevent us from posting status updates as often we'd like, but this issue will remain open until the "Good, not Evil" clause is removed.

**Comment by pravi** [comment]
@jugglinmike its about 11 months since the last comment. I'd like to know the current status of this issue.

**Comment by andreicristianpetcu** [comment]
Seriously? Another "Good, not Evil." license? What is the point of this? Please pick a real FSF approved or OSI approved license.

**Comment by flying-sheep** [comment]
@andreicristianpetcu: you're unnecessarily antagonistic because you're uninformed.

do you know what  jshint was forked off? once you do, carefully read this thread, then please apologize for the previous comment.

**Comment by andreicristianpetcu** [comment]
@flying-sheep I read the thread. Sorry for the spam.

**Comment by eclipseo** [comment]
Any progress on this issue? It's preventing us from including  it in Fedora.

**Comment by jugglinmike** [comment]
Thanks for your interest, @eclipseo. I'd love for JSHint to be included in Fedora! Right now, we're trying to re-write a few targeted sections of the codebase. I cannot contribute directly due to my familiarity with the non-Free code. The same goes for many of our prior contributors, so I've been searching for new people with a passion for free software and a penchant for JavaScript. If you (or anyone else following along) know of anyone that fits the bill, please ask them to contact me (either on this thread or via my personal e-mail address).

**Comment by andreicristianpetcu** [comment]
Well.... if it's written from scratch it does not matter who writes it. This is a copyright issue, not a patent issue.

**Comment by jugglinmike** [comment]
We are not currently attempting to re-write from scratch. I tried to communicate this in my previous response with the phrase, "a few targeted sections of the codebase."

**Comment by bastien-roucaries** [comment]
What is the current status ?

**Comment by ajakaja** [comment]
> The same goes for many of our prior contributors, so I've been searching for new people with a passion for free software and a penchant for JavaScript. If you (or anyone else following along) know of anyone that fits the bill, please ask them to contact me (either on this thread or via my personal e-mail address).

Just came across this issue -- are you still looking for help?

**Comment by jugglinmike** [comment]
@ajakaja I am! Could you e-mail admin@jshint.org ?

**Comment by ranolfi** [comment]
I approve of the author remaining true to his original commitment. If this was my creative work I would also hold the Not Evil clause to the end.
The clause is open to interpretation (and certainly won't hold in court, nor was the author's intend that it ever could, I'm sure) for a reason. And the reason might be a moral one, a sense of humor, or probably a mixture of both.

Now if some distro can't include the software in its repos because the definition of "free software" they insist to abide to is excessively strict - _or shall I say narrow-minded_, that is just too bad.

Good job @douglascrockford and project maintainers.

**Comment by jugglinmike** [comment]
Good news, everyone! We've just published JSHint 2.12.0, the first version to be completely licensed under the MIT Expact license. [Details about the process are available on the project website.](https://jshint.com/relicensing-2020/index.html)

If anyone is still interested in packaging JSHint for a software repository, I'll be happy to help!
