### ISSUE TITLE
Firefox doesn't hoist functions in blocks, warn when I put a function in a block

### ISSUE THREAD

**Issue by robrich** [jshint/jshint#1257]
Firefox does things differently than other browsers.  It doesn't hoist functions declared inside blocks.  Consider this code:

	if ( true ) {
	    testFunction();
	    function testFunction() {
		alert(‘testFunction called’);
	    }
	}

Other browsers run this just fine.  Firefox fails because testFunction() isn't defined.  See http://statichtml.com/2011/spidermonkey-function-hoisting.html

Please warn when I put a function in a block or provide me an option to do so.

Note that this is different than `latedef` because declaring the function outside the block at the bottom of the file works just fine.

**Comment by lukeapage** [comment]
@jugglinmike this now errors "Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function." on master. Can this be closed?

**Comment by jugglinmike** [comment]
@lukeapage That error has been in place (in one form or another) since JSLint was originally open-sourced:

https://github.com/jshint/jshint/blob/ca120a731db548c0014320fa0c196edc613536ae/fulljslint.js#L4855-L4859

So I'm confused as to how this problem surfaced in the first place. Because we haven't heard from any other users in the 18 months since this bug was filed and because I can't reproduce the reported behavior for any version of JSHint, including 2.1.10 (the latest at the time of the initial report), I think it's likely a mistake on the part of the reporter. I'll close this for now, but I encourage anyone that stumbles across this issue in the future to make some noise here.
