### ISSUE TITLE
Globals for TDD frameworks (mocha, jasmine)

### ISSUE THREAD

**Issue by deniswolf** [jshint/jshint#1330]
Since contribution guide requires issue before commit && because I want to get approval first:

It seems like every JS project created since 2010 has to add _describe_, _it_ etc to global.
Can we add globals for Jasmine and Mocha to whitelist, please?
Or, if you don't want to pollute globals, some generic 'tdd' option with at least _describe_ and _it_ could be great.

**Comment by ajssd** [comment]
The trouble with the mocha global (describe, it, etc.) is that it combines TDD and BDD.  

If you follow the official recommendation of selenium-webdriver and Mocha here
https://code.google.com/p/selenium/wiki/WebDriverJs#Writing_Tests

you will get a lint error on "test = require('selenium-webdriver/testing')" because "test" is being redefined.  It's defined once using the "mocha" global in .jshintrc, and again here.  This could be solved if the TDD and BDD globals were made distinct, e.g. "mocha-bdd": true.  
![ss](https://cloud.githubusercontent.com/assets/10245941/5622424/4b78f0dc-94f8-11e4-947a-a564f7d4b669.png)
