### ISSUE TITLE
[DOC] Missing exported and globals from documentation

### ISSUE THREAD

**Issue by dotnetCarpenter** [jshint/jshint#1459]
I was just looking through the [documentation](http://www.jshint.com/docs/options/) and had to google both a `/* global ... */` example and how to suppress functions used by other code. I then found [an answer on SO](http://stackoverflow.com/questions/8852765/jshint-strict-mode-and-jquery-is-not-defined/8854093#8854093) and #659.

It would be nice if **directives** was mention in the options page. I realize it was my bad not finding them on the main [documentation page](http://www.jshint.com/docs/) but I came to jshint from a link on cloud9 and I'm guessing others will have the same entry.

**Comment by jugglinmike** [comment]
The `globals` option is now documented on [jshint.com's "options" page](http://jshint.com/docs/options/). It includes a reference to the corresponding directive ("To configure globals within an individual file, see [Inline Configuration](http://jshint.com/docs/#inline-configuration).") The `exports` directive continues to be documented with the other directives, but because it has no associated configuration option, it does not belong on the "options" page.

Thanks for the report!
