### ISSUE TITLE
Support for Meteor.JS

### ISSUE THREAD

**Issue by dandv** [jshint/jshint#1534]
Here's a [list of globals](https://github.com/dandv/Meteor-jshintrc/commit/697ebf8b8f8ca5b85e48d6305994b791c1966002). Hope it helps!

**Comment by lukeapage** [comment]
Sorry,  its a slippery slope supporting globals for every library.

**Comment by raix** [comment]
I've added a pr. https://github.com/jshint/jshint/pull/2684 adding the meteor platform to jshint.

*I haven't added the distribution since the build script updated a lot of unrelated stuff, preferred to keep the pr. clean*

Ref: https://github.com/meteor/meteor

Please let me know if you have any  questions,

Kind regards Morten
