### ISSUE TITLE
 Allow multiple reporters for a single run

### ISSUE THREAD

**Issue by dharkness** [jshint/jshint#1702]
When running JSHint in Jenkins, we want the regular output for the build log (emailed to developers for quick fixes) and the `checkstyle` reporter for the Jenkins Checkstyle plugin to process.

Is this possible? If not, it would be very handy so we don't have to run JSHint twice.

**Comment by robertlevy** [comment]
@valueof - would the team consider a PR for this?

**Comment by jsr6720** [comment]
@jugglinmike @valueof 
Any additional work required to merge in pr #2727 
I know this is tagged P4, but @Paychex would love to use it as designed.

**Comment by mageddo** [comment]
I think that it is very usefull, please consider

**Comment by GenYDeveloper** [comment]
I think this would be useful as well, especially for developers using npm-scripts over Grunt or Gulp.

**Comment by jugglinmike** [comment]
Hey all, I've been thinking about this, and I believe you can get what you want
without modifying JSHint at all!

[The reporter API](http://jshint.com/docs/reporters/) is incredibly simple
(maybe even too simple, but that's a discussion for another thread). Reporters
are Node.js modules that adhere to a simple protocol: "define a `reporter`
method."

That makes defining reporters easy, but it also makes simple composition of
reporters a snap. If you would like to use two (or more!) reporters, say
`first-reporter` and `second-reporter`, you could make your own reporter that
simply hooks them together:

```js
var first = require('first-reporter');
var second = require('second-reporter');

exports.reporter = function(results, data, opts) {
  first.reporter(results, data, opts);
  second.reporter(results, data, opts);
};
```

Save that to `dual-reporter.js` and run JSHint with:

    $ jshint --reporter ./dual-reporter.js

...and you should see the output of `first-reporter` followed by the output of
`second-reporter`.

This approach is way more flexible than extending the CLI because it allows you
to perform more advanced operations on the output. The use case (as I
understand it) is to send the different reports to different places. Extending
the CLI to support a list might be a little more convenient than writing a
"wrapper" reporter, but you still have to deal with de-multiplexing the two
streams of output.

With this approach, you can either (1) output a custom delimeter between the
reports, or (2) stub out `process.stdout` between reporter invocations with
another stream of your choosing, obviating the need to post-process altogether.

What do you think?

**Comment by jsr6720** [comment]
@jugglinmike it makes sense, but it's not as clear from a configuration stand point. instead of looking at execution and seeing --reporters=firstReporter,secondReporter I see dualReporter then I have to go look at the file. At this point I'll take any solution over none. Thanks for pointing it out. Does this mean PR #2727 is out?

**Comment by jugglinmike** [comment]
I'm afraid so, @jsr6720. In an effort to make this solution more discoverable,
I'm proposing an addition to JSHint's "Frequently-Asked Questions" document:

https://github.com/jshint/jshint.github.io/pull/37

If you have any thoughts on how that might be improved, please let me know!

**Comment by atdiff** [comment]
@jugglinmike is it possible to have multiple reporters that go to different reporterOutput?  For instance, I want the jshint results to go to the standard console output as well as be put into a file.  I see the concept of multiple reports, but I'm not sure how to make my idea happen in that context.
I'm currently using options of to get it into a file:
`options: { 
 reporter: 'checkstyle',
 reporterOutput: './src/test/reports/static_analysis/jshint-jslint-report.xml',
 reporterOutputRelative: false
}`

I could just have 2 targets, but that duplicates running the jshint process over the same files.  Whereas it'd be nice to just have the results go to 2 different output locations (console and file).
