### ISSUE TITLE
Experimental Traceur features/ES7

### ISSUE THREAD

**Issue by OliverJAsh** [jshint/jshint#1939]
One experimental/ES7 feature supported through Traceur that I want to start using today is [async/await](jakearchibald.com/2014/es7-async-functions/).

What is JSHint’s stance on supporting experimental Traceur features i.e. ES7, e.g. `async/await`?

**Comment by IanVS** [comment]
Hi, I read through a few pull requests and issues regarding support of ES7 async/await, but it seems the conversation has died off.  Has there been any other thinking or progress towards support in some shape or form?

**Comment by abrkn** [comment]
:+1:

**Comment by jugglinmike** [comment]
Nothing's been discussed off-line--the conversation on GitHub is the extent of it

**Comment by IanVS** [comment]
Do I understand correctly then that async/await won't be handled (supported or ignored) until a plugin system is developed?

**Comment by jugglinmike** [comment]
Please remember that the async/await is a proposal for a far-future version of the language and not a specification. Beyond the initial development effort, extending JSHint core with support for this syntax would be a burden on both the maintainers and the consumers. Changes to the proposal will need to be reflected in the user's platform (whether a runtime or a transpiler), the user's code, and also in JSHint itself. It would be hard enough for JSHint to synchronize updates with platform changes, but the problem becomes intractable when you recognize that the userbase will upgrade incrementally. (Proposal changes might seem unlikely, but we're even today struggling with last-minute modifications to ES6's module syntax--see gh-2019 and gh-2036 for a couple examples.)

This is why prior to standardization, the healthiest way for JSHint to support this syntax would be through a plugin system. Once this feature approaches standardization, I expect JSHint's core will be extended to support it natively (just as is happening with ES6 features today).

@rwaldron @caitp @mikesherov If this reasoning reflects your thoughts, I think it would be best to close this issue.

**Comment by sebv** [comment]
How long for the plugin system to emerge?

**Comment by CrabDude** [comment]
I certainly appreciate how a request to support async/await may feel like a burden on the JSHint contributors, but I just wanted to provide my perspective and nothing more to encourage support in spite of @jugglinmike's stated concerns:

With the rise in popularity of transpilers (with support for async/await) like traceur and especially babel, the flood of increasingly standardized ESNext features (further encouraging the use of transpilers), the proliferation of promises, and the present support for generators in node.js and io.js (which makes async/await sugar for function* instead of a hack), async/await will see a dramatic increase in usage in the near future.

Further, the popularity of talks like @jhusain's excellent ES7 talks at NodeDay and NodeSummit add to the async/await excitement. At Noderiety and the companies I partner with for node.js training, we're teaching generators/promise first development, and the only thing limiting teaching async/await first is JSHint support.

So obviously I'm bias, but the presence of async/await causes JSHint to go crazy, and makes it almost unusable (admittedly, not the fault or responsibility of the JSHint project). Something as simple as just ignoring (or stripping when linting) the async/await keywords would at least make it possible to use both async/await and JSHint together.

Please consider providing some minimal hack or workaround to at least make JSHint and async/await not incompatible, or consider leaving this issue open and providing some guidance on how to add such a workaround in a manner that would be successfully merged.

 Thanks.

**Comment by CrabDude** [comment]
For anyone in the same boat as me, I was able to get `eslint`, `babel-eslint` and `SublimeLinter-eslint` working.

**Comment by IanVS** [comment]
@CrabDude thanks, that is also the direction I am moving.

**Comment by rwaldron** [comment]
> Something as simple as just ignoring (or stripping when linting) the async/await keywords would at least make it possible to use both async/await and JSHint together.

This has been suggested and I'm all for it.

**Comment by CrabDude** [comment]
@rwaldron Excellent. At least this would change this issue from a "wontfix" to an open issue to ignore async/await keywords until it is finalized, for the happy fellow that has time to implement it, wherever he may be. =)

**Comment by callumlocke** [comment]
@CrabDude 
> For anyone in the same boat as me, I was able to get eslint, babel-eslint and SublimeLinter-eslint working.

thank you for pointing me in the right direction

**Comment by billinghamj** [comment]
I'd really like to see some solution for this. Currently it makes JSHint a bit unusable as it just ends up saying "Too many errors".

**Comment by jugglinmike** [comment]
@billinghamj You can read more about this issue here: http://jshint.com/blog/new-lang-features/ . In the short-term, your best bet is JSHint's `ignore` directive. You'll be happy to know that async/await advanced to "stage 2" of TC-39's proposal process, meaning it is now on the docket for experimental/unstable implementation in JSHint.

**Comment by billinghamj** [comment]
@jugglinmike Is it possible to put "ignore" in the config and get it to ignore "async" and "await" as keywords entirely?

**Comment by lukeapage** [comment]
@billinghamj nope, sorry.

**Comment by lukeapage** [comment]
@jugglinmike has raised this clear proposal - https://github.com/jshint/jshint/issues/2601 which supersedes this. I'm closing for clarity (there are alot of old comments on this issue)
