### ISSUE TITLE
Missing semicolon warning on closures with asi: true

### ISSUE THREAD

**Issue by MikaAK** [jshint/jshint#2091]
Even with `asi: true` the following will still complain about a missing semicolon, however the second case will not, with `asi: true` it shouldn't complain about this missing semicolon as per #1906 

```
'use strict'

(function() {
})()
```

```
'use strict'

function() {
}
```

**Comment by caitp** [comment]
```
'use strict'

(function() {
})()
```

is not valid javascript, which is why we emit an error here.

**Comment by caitp** [comment]
you there? I don't think this is actionable, because we shouldn't let this obvious error sneak through unscathed by the ASI option :p I hope this makes sense

**Comment by MikaAK** [comment]
@caitp I'm a bit confused, how is this not valid javascript vs the second case?

**Comment by caitp** [comment]
@MikaAK well, it is "valid javascript", but it will always produce a runtime error as strings do not have a `[[Call]]` internal method (but the `IsCallable()` algorithm always returns false for primitives anyways).

Anyways, automatic semicolon insertion does not apply here, because the string itself does not terminate the ExpressionStatement.

So,

```
"use strict" // no problem, semi-colon is inserted :D
"some other string"
```

```
"use strict" // Oops, we're trying to "call" the string, because the ExpressionStatement
             // looks like a function call!
(...);
```
