### ISSUE TITLE
How to --exclude from API (not ABI)?

### ISSUE THREAD

**Issue by MoOx** [jshint/jshint#2126]
Can't find anything in the doc about how to exclude from api (without any .ignore).
Is there any?

**Comment by jugglinmike** [comment]
I don't understand what you are asking here. Could you share an example that demonstrates your problem?

**Comment by MoOx** [comment]
I can do `jshint . --exclude src/lib` but cannot do the same with js api. Is this more clear?

**Comment by jugglinmike** [comment]
I think so. Are you saying that you would like to exclude more than one directory?

**Comment by MoOx** [comment]
No I mean I would like to do the same from js

```js
var jshint = require("jshint").JSHINT
var result = jshint(source, {exclude: ["src/lib"]})
```

Is this working, can not find doc anywhere (also, didn't try).

**Comment by jugglinmike** [comment]
When you use JSHint from the command line, you specify file names that it should read from the local disk. The `exclude` flag allows you to black-list specific files.

When you use JSHint via its JavaScript API, you specify JavaScript source code directly. Because you are providing the source code (and not files), JSHint itself is not aware of file names--it simply lints whatever code it is given. In this case, if you would like to black-list specific files, you would need to implement some condition in your own script.

Does this make sense?

**Comment by MoOx** [comment]
Yeah. Indeed. I were looking in the wrong place (I'm using jshint-loader for webpack, so I exclude from the loaders via a pattern). Thanks anyway!
