### ISSUE TITLE
Inline global declaration doesn't work with single-line comments

### ISSUE THREAD

**Issue by izeau** [jshint/jshint#2135]
There's a catch in the inline global declaration: it doesn't work with single-line comments.

```
// This will fail
// global createjs: false

// This will pass
/* global createjs: false */

createjs.Sound.registerSound(foo, bar);
```

This is not consistent with other jshint inline configuration that can be declared with single-line comments, e.g:

```
// jshint opt
```

**Comment by rwaldron** [comment]
JSHint can irrefutably claim ownership of the word "jshint" and subsequently any use of the word in any comment form. JSHint cannot claim ownership of any other word, because there is no way to unambiguously parse. Consider the following: 


```js
// global booleans: true by default.
var a = true;
var b = true;
```

Was the intention to tell JSHint that a binding named "booleans" exists globally, or is it indicating to readers of the source that all global bindings, whose value is a boolean, will be declared `true` by default?

**Comment by izeau** [comment]
That's a very good point indeed. Can we specify that behavior in the documentation?

**Comment by rwaldron** [comment]
@izeau sure! File here: https://github.com/jshint/jshint.github.io

**Comment by VsevolodGolovanov** [comment]
> That's a very good point indeed.

But the same pitfall applies to multi-line comments...
