### ISSUE TITLE
Object destructoring variable reuse

### ISSUE THREAD

**Issue by megawac** [jshint/jshint#2269]
```js
let {start, stop} = node;
// ...
({start, stop}) = othernode;
```

Throws 2 errors:
  - bad assignment
  - Expected an assignment not an expression

Sorry if its a dupe, only glanced through issues

------

It's valid according to the folks at babel

[Repl example](https://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=let%20%7Bstart%2C%20stop%7D%20%3D%20node%3B%0A%2F%2F%20...%0A(%7Bstart%2C%20stop%7D)%20%3D%20othernode%3B)

**Comment by caitp** [comment]
This does not appear to be valid. On mobile, but it looks like the binding pattern is supported only in declarations, for loops, catch parameters, and formal parameters. Does not appear legal as an assignment lhs (@rwaldron correct me if I'm wrong!)

**Comment by megawac** [comment]
It's valid according to the folks at `babel`

**Comment by caitp** [comment]
Not valid according to traceur --- I'll give the spec a closer look when I get home, but it doesn't look valid to me from the st Patrick's day draft

**Comment by caitp** [comment]
hmm, I think you're right about this --- we're only supporting BindingPatterns, but not AssignmentPatterns, it looks like.

**Comment by rwaldron** [comment]
> It's valid according to the folks at babel

Just to be clear: Babel is not infallible; but in this case yes, that code is valid. 

Here's a test case: 

```js
var a = {start: 1, stop: 2};
var b = {start: 3, stop: 4};
var c = [5, 6];
var {start, stop} = a;
({start, stop}) = b;
([start, stop]) = c;
```

**Comment by caitp** [comment]
yep, chop it up to text searching in mobile safari being really difficult :>

**Comment by rwaldron** [comment]
Impossible!

**Comment by arv** [comment]
This is valid in SpiderMonkey but it is not valid in ES6.

**Comment by caitp** [comment]
Based on what? I looked pretty hard for a reason it's not legal. Bugs should be filed to have the draft clarified, if it is not

**Comment by caitp** [comment]
Okay, there have been no answers here, so I've done a bit more research:

`[a, b] = [1, 2]` is valid, because `[` is unambiguously the start of an ArrayLiteral (re-parsed as an ArrayAssignmentPattern) as the first symbol of a statement expression. This does not hold for `{a, b} = {a: 1, b: 2}`, because of ambiguity with a block (from [13.4](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-expression-statement)).

`({a, b} = {a: 1, b: 2});` is however, perfectly legal --- parenthesizing the entire binary expression means it's not ambiguous with a Block. Unfortunately for this bug, `({a, b}) = {a: 1, b:2};` is not legal on these grounds (the supplemental grammar does not work here, either because the ParenthesizedExpression is not a valid destructuring target ([12.3.1.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-static-semantics-static-semantics-isdestructuring)), or because there are tokens left over when parsing the parenthesized ObjectLiteral as an ObjectAssignmentPattern ([12.14.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators-static-semantics-early-errors)). Take your pick which of these reasons are more important, or find other ones if you care to.

---

Again, I'm not infallible, and have not been able to get through the entire draft from top to bottom yet (one day, though, one day) --- so it's possible that this reasoning is incorrect.

If these reasons are correct, there may be (or ought to be) a bug filed on SpiderMonkey and Babel.

**Comment by arv** [comment]
That's pretty much correct. There is no grammar that allows parenthesized patterns as a left hand side expression.

**Comment by guyzmo** [comment]
hey, saw you were talking about a bit of code I wrote at some point, and to me it looks the expression:

    ({a, b}) = {a: 1, b: 2};

looks really weird. Following last @caitp's comment on this, it looks like this is an issue of standard vs implementation. But jshint is not about interpreting/running code, it's about analysis. 

So the real issue here would be to make it possible to parse such a construct to warn the user against it, and informing him that: it's not valid against standard, but might work against spidermonkey, so it is not recommended.

I'd even get further and wonder whether: 

    ({a, b} = {a: 1, b: 2});

shouldn't be something warned against, as even though it's "legal", is it really a good practice?

Though, the downside of doing such warnings, it might increase the complexity of the parser for the extra parenthesis check :-/

This is my two cents :-)

N.B.: *I'm lurking most of the discussions happening here, more closely when the title is obvious about an ES6 stuff I've participated in, but as over the last 2 years, I'm having a job taking 120% of my time, I cannot participate as much as I'd like and get through all the incoming mails, so don't hesitate to ping me on IRC to come in whenever there's a question, or whenever my input can help on a code I'm guilty of :-)*

**Comment by caitp** [comment]
I wouldn't want to encourage people by saying it might work in SpiderMonkey -- I filed a bug about this a few hours ago, so hopefully it will be fixed in a few weeks

**Comment by rwaldron** [comment]
> [a, b] = [1, 2] is valid, because [ is unambiguously the start of an ArrayLiteral (re-parsed as an ArrayAssignmentPattern) as the first symbol of a statement expression. This does not hold for {a, b} = {a: 1, b: 2}, because of potential for ambiguity with a block (from 13.4).

This is how I rationalized `({ a, b }) = {a: 1, b: 2};`, by assuming the same rules that allow `({ a: 1 }).a === 1`. I was also (possibly incorrectly) further convinced because SpiderMonkey implemented the syntax as I had interpreted it. We need help—paging @allenwb @anba :)

**Comment by allenwb** [comment]
@rwaldron believe the spec. 
_AssignmentExpression_ : _LeftHandSideExpression_ = _AssignmentExpression_
has little in common with:
_MemberExpression_ : _MemberExpression_ . _IdentifierName_

In particular the early error rules in http://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-assignment-operators-static-semantics-early-errors apply to _AssignentExpression_.

And when the spec. says _ObjectLiteral_ it means _ObjectLiteral_ not a parenthesized _ObjectLiteral_. 

I believe that the spec. once explicitly allowed for parenthesized _AssignmentPatterns_ as the LHS but it was changed after discussion at TC39 meetings.  It was seen as an unnecessarily complication and generally parenthesized LHS were seen as undesirable (even though they are required for compat with legacy code).

**Comment by rwaldron** [comment]
> @rwaldron believe the spec. 

A fair dose of my own advice. Thanks for your help.

**Comment by sebmck** [comment]
Just so I'm clear, does that mean that the following:

```javascript
var a = 1;
(a) = 2;
```

is actually illegal according to the spec?

**Comment by caitp** [comment]
no, https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators-static-semantics-early-errors covers the cases where you get an error here.

IsValidSimpleAssignmentTarget for `(a)` returns true, (https://people.mozilla.org/~jorendorff/es6-draft.html#sec-identifiers-static-semantics-isvalidsimpleassignmenttarget and https://people.mozilla.org/~jorendorff/es6-draft.html#sec-semantics-static-semantics-isvalidsimpleassignmenttarget)

**Comment by sebmck** [comment]
Thanks @caitp :)

**Comment by lukeapage** [comment]
@caitp please could you take a look at the following (simple) test case and let me know if there is anything wrong ?

valid:
```
let b;
[b] = b;
([b] = b);
({b} = b);

let c = {b} = b;
c = [b] = b;
c = ({b} = b);
c = ([b] = b);
```
invalid:
```
let b;
{b} = b;
({b}) = b;
([b]) = b;

let c = ({b}) = b;
c = ([b]) = b;
```

**Comment by lukeapage** [comment]
array destructuring currently works, but is flawed because any inner objects are parsed using object literal parsing and then interpreted as destructuring afterwards, e.g. jshint thinks this is good code:

```
let b;
([{constructor(){}}] = b);
```

**Comment by lukeapage** [comment]
branch started, early feedback welcome
https://github.com/lukeapage/jshint/tree/destruct-assignment

**Comment by caitp** [comment]
So what we (are in the process of) do(ing) in v8 is, we have an expression classifier object which tracks locations where errors for different ways of parsing something happen, so that we know to report an error later once we know which "thing" we're actually parsing. So if we see a MethodDeclaration, we report that it's a bad BindingPattern and AssignmentPattern, and keep going. It would be hard to use the same approach here, and it would make the parser even more confusing, but it's something we could try

**Comment by lukeapage** [comment]
Yep, i read about that in relation to arrow functions. Its a cool approach
but might be out of scope for here. Lots of existing code would need
refactoring.
