### ISSUE TITLE
Add GreenSock-JS globals?

### ISSUE THREAD

**Issue by stevemao** [jshint/jshint#2336]
Hi I'm currently working with GreenSock-JS (https://github.com/greensock/GreenSock-JS) and they have a bunch of globals (http://greensock.com/forums/topic/11369-gsap-globals-for-jshint/) 

```js
"globals": {
        //GSAP Globals
        "TimelineLite" : false,
        "TimelineMax" : false,
        "TweenLite" : false,
        "TweenMax" : false,
        "Back" : false,
        "Bounce" : false,
        "Circ" : false,
        "Cubic" : false,
        "Ease" : false,
        "EaseLookup" : false,
        "Elastic" : false,
        "Expo" : false,
        "Linear" : false,
        "Power0" : false,
        "Power1" : false,
        "Power2" : false,
        "Power3" : false,
        "Power3" : false,
        "Power4" : false,
        "Quad" : false,
        "Quart" : false,
        "Quint" : false,
        "RoughEase" : false,
        "Sine" : false,
        "SlowMo" : false,
        "SteppedEase" : false,
        "Strong" : false,
        "Draggable" : false,
        "SplitText" : false,
        "VelocityTracker" : false, 
        "CSSPlugin" : false,
        "ThrowPropsPlugin" : false, 
        "BezierPlugin" : false
}
```

I wish I could just write

```js
GSAP: true
```

**Comment by jugglinmike** [comment]
Accepting library-specific globals is a slippery slope of supporting all sorts of lesser-used libraries. Instead of trying to define which libraries are "popular enough" to justify inclusion, we're reserving new environment settings for true environments.

The GreenSock library might consider exporting a single variable on the global scope and using that as a namespace for its API. I only suggest changing the source code (instead of JSHint) in this case because the change would do more than address this specific problem (making linting configuration easier to manage). It's generally considered a best practice because it minimizes risk of collisions and it requires consuming code to be easier to follow (the origin of every method is communicated each time it is accessed).

**Comment by stevemao** [comment]
I can't agree more :D

**Comment by jugglinmike** [comment]
Thanks for understanding!
