### ISSUE TITLE
label shadowing is a syntax error but is only warned under shadow inner

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2419]
from discussion here: https://github.com/jshint/jshint/issues/2394#issuecomment-106620733

The following code:
```
/* jshint shadow:true */
a: while (true) {
  a: while (true) {}
}

function b() {
  c: while (true) {
  	c: while (true) {}
	}
}
```

does not error, even though it is a syntax error. With `shadow: inner` the 2nd case will warn.

**Comment by jugglinmike** [comment]
The behavior in `master` (2c0dc5e7bdb865ca31b903f6eb487bbb45f49e55) seems to have changed. I can now only trigger the expected warning when `shadow` set to `outer`.

This code does not trigger an warning:

```js
(function() {
  label: while(true) {
    label: while(true) {}
  }
}());
```

but this does:

```js
// jshint shadow: outer
(function() {
  label: while(true) {
    label: while(true) {}
  }
}());
```

In the most recent release (2.8.0), *both* versions trigger a warning, as expected. Because of this, I'm adding the "Regression" label to this issue.

**Comment by lukeapage** [comment]
I added a comment to the test saying it was wrong, I must have thought it was existing behaviour or forgotten to write TODO next to it.
