### ISSUE TITLE
Dist for 2.8.0 says 2.7.0

### ISSUE THREAD

**Issue by cfjedimaster** [jshint/jshint#2432]
In the distribution for 2.8.0, the comment on top still says 2.7.

**Comment by jugglinmike** [comment]
Looks like I made a mistake when building the release. The best we could do is publish version 2.8.1 to fix the comment, but since it is purely cosmetic (the source code itself is, in fact, version 2.8.0 of JSHint), I don't think there's much value in doing so.

Thanks for the report! I'll see what I can do about improving our release infrastructure so we avoid this in the future.
