### ISSUE TITLE
inline if statement produces errors

### ISSUE THREAD

**Issue by Gamesh** [jshint/jshint#2479]
```javascript
        toggle: function () {
            this.isActive() ? this.hide() : this.show();
            return this;
        }
```
jshint v.2.8.0, outputs error:
```
Expected an assignment or function call and instead saw an expression.
```

if the same code is replaced with non inline if statement's, it does not produce this error.
i'm thinking this is a false possitive

**Comment by lukeapage** [comment]
Please see this option
http://jshint.com/docs/options/#expr

It is a warning because you are using an expression to have side effects, which could be down to buggy code. Some people might argue that

```
if (this.active()) {
    this.hide();
} else {
    this.show();
}
```
is more expressive and easier to understand, but that is subjective, hence the reason for it being an option.

**Comment by Gamesh** [comment]
thanks, was not sure if weather this was a bug or not and didn't find any reports like this in the issues
