### ISSUE TITLE
ES7: async and await

### ISSUE THREAD

**Issue by peduxe** [jshint/jshint#2504]
Is there any support for those? I saw some discussions about implementing this but there wasn't a final consent.

**Comment by nicolo-ribaudo** [comment]
Related/Duplicated: #1939

**Comment by peduxe** [comment]
Yeah, I tried using the `experimental` json key-value but it didn't work.

**Comment by caitp** [comment]
there is no "experimental" option yet, sorry. Anyways, this is a duplicate, lets keep it to the original issue.

The way jshint's parser is built does not make it very nice to support "experimental" features that may never make it as far as stage 2, or may change drastically before being ratified. It's very brittle, unlike projects such as Traceur or Babel which are built on traversing and transforming an AST. I hate to say it, but maybe eslint is the preferred solution for linting these experimental features, due to its AST-linting.

**Comment by slokhorst** [comment]
For the current status, see #2604

**Comment by nodesocket** [comment]
`async/await` are now supported as of version `2.10.1`. Simply update your `.jshintrc` to use `"esversion": 9`.

See the [CHANGELOG.md](https://github.com/jshint/jshint/blob/master/CHANGELOG.md).
