### ISSUE TITLE
dont warn using optional semicolons in classes

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2578]
I was reading http://hacks.mozilla.org/2015/07/es6-in-depth-classes/ and it occurred to me we perhaps shouldn't  warn about unnecessary semicolons in classes e. g. 
```
class a {
  b() {} ;
} 
```

**Comment by nicolo-ribaudo** [comment]
Does JSHint ignore some other places where the semicolon is unnecessary?

**Comment by lukeapage** [comment]
I don't think so. I was just surprised seeing a mozilla dev advocating a semi-colon style for classes. I haven't seen anyone advocating semi-colons for function declarations though.

**Comment by jugglinmike** [comment]
Warning W032 describes this usage perfectly, so it is definitely appropriate.
It may not be tenable for users to disable W032 by name for just this case
(since that directive would also apply the bodies of class methods), but we
have no indication beyond that blog post that this is a common usage.

If anyone would prefer to use semicolons in this way, please comment here. With
enough interest (and preferably some rationale put in terms of code safety), we
could justify a change here--either removing the warning or the introduction of
a dedicated linting option.
