### ISSUE TITLE
Illogical `typeof` error for variable's property

### ISSUE THREAD

**Issue by jacksonrayhamilton** [jshint/jshint#2646]
On `v2.8.0` and `master`, for the following file:

```js
/* jshint undef: true */
if (typeof exports === 'object' && typeof exports.nodeName !== 'string') {}
```

I get the following error: "script.js: line 2, col 43, 'exports' is not defined."

Logically, `exports` should be acceptable in the second part of the condition. Is this a limitation of static analysis?

**Comment by mikesherov** [comment]
Definitely a limitation of static analysis because there are literally infinite constructs that can semantically cause one to be able to reason that a variable must be defined later in the code:

```
typeof exports !== undefined && ...
!!exports && ...
!!!!exports && ...
exports && ...
if (exports) ...
const defined = (value) => typeof value !== undefined; defined(exports) && ...
```

This is why jshint has the `/* global variableName */` directive, to indicate the possible presence of a global in a static analysis context that otherwise would require dynamic analysis.

Can I close this issue?

**Comment by jacksonrayhamilton** [comment]
Yep, a `global` directive seems to be the best solution.
