### ISSUE TITLE
Shorthand to ignore unused variables in destructuring assignment and formal parameter lists

### ISSUE THREAD

**Issue by ptomato** [jshint/jshint#2729]
I often have code like this:
```js
let [valueIDontCareAbout, importantValue] = getSomeValues();
doSomethingWith(importantValue);
```
or
```js
function myCallback (paramIDontCareAbout, importantParam) {
    doSomethingWith(importantParam);
}
```
There are several customary shorthands to show that a parameter is unused on purpose and it would be cool if jshint understood some of them and did not warn about unused variables (W098). Examples:
```js
let [_a, _b, c] = ...
let [a /* unused */, b /* unused */, c] = ...
```
Array elisions would also work there but they can get hard to read if there are a lot of parameters elided.

#2352 seems to be a similar issue, but this is about jshint understanding existing idioms rather than an extra configuration option.

**Comment by nicolo-ribaudo** [comment]
>
```js
let [valueIDontCareAbout, importantValue] = getSomeValues();
```

If you don't like elisions, you can do something like this:
```js
let [/* valueIDontCareAbout */, importantValue] = getSomeValues();
```


>
```js
function myCallback (paramIDontCareAbout, importantParam) {
    doSomethingWith(importantParam);
}
```

If you use `unused: true`, JSHint doesn't warn about unused parameters followed by used parameters.

**Comment by jugglinmike** [comment]
To completely realize the expectations expressed here, the requested feature
would have to do more than allow the creation of unused bindings. It would also
have to warn about later references to those bindings--the developer does not
intend for them to be used, after all.

Overall, I think this practice would make code harder to read. If the intention
is to not use certain values, then it's far more natural to *not* create
bindings for those values. In this way, developers are not expected to
interpret some bindings as "safe to use" and others as "unsafe to use" (this
also avoids extra maintenance overhead for changing between these two states).

We're lucky here because (as discussed in gh-2352 and @nicolo-ribaudo's comment
above), the language itself exposes a syntax for making this distinction:
elisions. I can sympathize with the readability of long lists of elisions, but
I believe that concern is sufficiently addressed through the use of code
comments as placeholders.
