### ISSUE TITLE
Count multiple var statements as One in the count of statements for W071

### ISSUE THREAD

**Issue by jlchereau** [jshint/jshint#2787]
Some people prefer to use multiple var statements which is the default configuration for JSCS.
See http://benalman.com/news/2012/05/multiple-var-statements-javascript/

It is difficult to find a consistent value for maxstatements in .jshintrc if multiple var statements are not counted as one.

**Comment by jugglinmike** [comment]
The option's name (and it's description: "This option lets you set the max
number of statements allowed per function") both describe number of JavaScript
statements. Special-casing `var` statements like this would be surprising to
users who don't subscribe to the subjective argument in favor of that practice.

A separate option *might* be preferable, but I'm not so sure. One general
litmus test for new features is, "can I name this?" So far all I can think of
is `maxnonvarstatements` which is kind of a mouthful. More important than
aesthetics though, is the cognitive overhead of maintaining configurations with
two distinct options whose responsibility overlap.

We could mitigate that with a new option that modifies `maxstatements`;
something like `collapsebindings: true`, but I think options should be
independent whenever possible for discoverability/maintenance purposes.

A third idea would be to make `maxstatements` accept modifiers within the value
itself, e.g. `maxstatements: 20:collapsebindings`. This is probably the best
way to go although there isn't much precedence for the pattern.

Now that I've written all that, though, I'm starting to wonder if "number of
statements" is really a code safety/correctness concern. `maxstatements` may be
a good candidate for removal.

@mikesherov: you have a good sense for the appropriate separation; what do you
think?

**Comment by mikesherov** [comment]
maxstatements is of the same variety as maxdepth and maxcomplexity: a code quality metric. I do think it belongs in JSHint, as setting maxstatements helps keep functions small and readable.

My personal opinion is to close this as wontfix because a statement is a statement even if it's just a var declaration. It still introduces cognitive overhead to have to track variables, and the fix is still the same: make smaller functions.

If anything I'd add another new rule called maxbindings (or a better name) that tracks local bindings, so developers have another metric they can enforce but I personally wouldn't have it do anything fancy like subtract those declarations from max statements or anything.

**Comment by jlchereau** [comment]
HI, I am not sure I have been clear.

```
var a, b;
```

seems to count as 1 statement where as:

```
var a;
var b;
```

count as 2 statements.

My JS files are always built with a closure (AMD or else) and a list of generally at least 20-25 var statements to help uglification. As an example, see https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.calendar.js.

Some developers prefer ```var a,b;``` but others prefer ```var a; var b;``` for reasons explained here above. The code is the same, but the way jshint is currently designed it is difficult to control maxstatements over a project in the second case.

**Comment by mikesherov** [comment]
@jlchereau, you've been clear.

My point was that, yes `var a, b;` and `var a; var b;` are semantically equivalent, but they are still 1 and 2 statements, respectively. 

And even though you'd pass some chosen value for maxstatements with the 1 statement version but not the 2 statement version, the fact that there is a large enough statement count discrepancy means you're likely including too many local variables per function.

Keep in mind I can also change the code `c(); d();` to `c(), d()` and reduce the statement count by one without changing semantics. The comma operator in general is a sneaky way to reduce statement count.

**Comment by mikesherov** [comment]
With all that said, keep in mind that for the "large count of local variables inside of a closure pattern", you can use inline JSHint comments to locally allow exceptions to the rule.

**Comment by jlchereau** [comment]
@mikesherov thank you for your time.

I second your point about an unambiguous definition of *statement* but commas do not play well with debugging and multiplying JSHINT comments proves cumbersome to maintain especially when they are no more relevant.

So please consider a **ignoreMultipleVars** or **handleMultipleVarsAsOne** option on the wish list for further improvements considering your other priorities. I have no doubt some developers might consider it a useful addition to an already wonderful tool.

**Comment by jugglinmike** [comment]
We haven't seen any additional interest in functionality like this, so I am going to close this issue. The proposed API would warrant some additional discussion, and I'm still not convinced that the feature is entirely appropriate besides. If anyone is interested in contributing a patch with this feature, please let us know so that we can collaborate on the design and implementation.
