### ISSUE TITLE
A single missing comma causes 2 errors and 5 warnings

### ISSUE THREAD

**Issue by adambuczynski** [jshint/jshint#2824]
Currently, a single missing comma in an object declaration will trigger 7 different errors/warnings in jshint, rather than just detecting that a comma is missing and showing a single relevant error:

![ss](https://www.dropbox.com/s/7cj73zjok01e8ni/Screenshot%202016-01-05%2008.45.39.png?dl=1)

Not sure if it can be lumped together in one error for this particular case, but it would be a bit cleaner.

**Comment by caitp** [comment]
so, it's certainly possible to recover parsing as though an `,` were correctly inserted. The trouble is, doing this makes it harder to know when to terminate trying to parse an ObjectLiteral production.

So, if the closing brace is omitted by accident, we will keep trying to parse the entire script as property definitions, and you run into a whole lot of "expected `:`" errors.

I'm not sure it's worth it, especially since this particular syntax error is an early error in every VM, and does not require the code to be hit in order to be reported as such, so linting tools aren't really needed to catch it, imo

**Comment by jugglinmike** [comment]
Generally, it's difficult to intuit the author's intention in the case of invalid input. We do our best, but as @caitp explains, it's not always possible. The important thing is that the error is reported.

An alternative solution would be to support bailing in the first of errors (but not warnings). This could be implemented by reporters without a change to JSHint's core.

**Comment by adambuczynski** [comment]
Thanks for looking into it.
