### ISSUE TITLE
Disallow 'undefined' as parameter name

### ISSUE THREAD

**Issue by matthieusieben** [jshint/jshint#2832]
In earlier versions of JS, undefined could be overwritten to be anything (e.g. `undefined = null;`).
Modern browsers (ES5) don't allow this anymore.

But we still see `undefined` as parameter of IIFE:
```js
(function (undefined) {
  // undefined is really undefined here.
})();
```

Could you add an option to JSCS to disallow doing this?

**Comment by jugglinmike** [comment]
Since the global `undefined` binding is non-writable, an error will be produced
when attempting to re-assign it (in strict mode only). However, the example you
shared is creating a new binding in a higher scope, "shadowing" the global. This
is not an error (inside or outside of strict mode) in any browser to my
knowledge, and certainly not disallowed by ES5.

In fact, this is a common pattern for defensive programming. There's been talk
about refining the treatment of this pattern a bit (see gh-1604), but I don't
think we'll be disallowing it any time soon.

**Comment by matthieusieben** [comment]
This is indeed defensive programming and would not cause any error.

One may, however, want to prevent this kind of (today irrelevant) trick in their project's coding style policy. Isn't that what JSCS is about ?

**Comment by jugglinmike** [comment]
The pattern is still relevant today because it is not always possible to guarantee that global code is strict mode code. If there was some potential harm from the practice, then there would be a case for extending JSHint to allow users to prevent it. But if it's a purely stylistic concern, then you're in luck--the JSCS project already has you covered with [its `disallowIdentifierNames` option](http://jscs.info/rule/disallowIdentifierNames).

**Comment by jugglinmike** [comment]
Actually, I spoke too soon about that JSCS option. `disallowIdentifierNames` will disallow references as well as declaration/assignment, making it inappropriate for your use case.

**Comment by matthieusieben** [comment]
I also thought of `disallowIdentifierNames` first. But it didn't work for my purpose indeed.

I understand your point of view on this. Thanks for your time.
