### ISSUE TITLE
enforceall being deprecated

### ISSUE THREAD

**Issue by sebastien-mignot** [jshint/jshint#2892]
I have 2 problems with this : 

- I know it has the possibility to make warning appears on a code that did not change. But on the other hand, it really makes jshintrc file way clearer, and it also helps see what new checks are available in new jshint versions. Anyway people who don't want it can not use it, and people who have a proper management of development tools can use it (when an update is available, we always have a developer in charge of testing it, seeing if the new options are good, and modifying confi files accordingly). And most of the production guys I know will always prefer to have the most possible warnings, and opt out of the one they don't want ; instead of risking missing a bug.

- I paid a fucking bounty on bountysource to have this option added to jshint !! And you remove it on the next big release. And people from jshint spoke on the ticket, saying "good idea" to this feature, but advising me to give a bounty if I wanted to see it done soon. This is really the kind of thing that removes all confidence in bountying for open source features...

**Comment by jugglinmike** [comment]
Hi Sébastien!

> And you remove it on the next big release.

The feature whose development you funded has not been removed yet.  gh-2045 is
an ongoing discussion about the removal, so there is still an opportunity to
influence that decision.

> This is really the kind of thing that removes all confidence in bountying for
> open source features...

I can appreciate why you feel betrayed, but I don't think this is cause for
discouragement. The fact that there has been an open discussion on the topic
spanning over a year (again, see gh-2045) demonstrates the team's reluctance to
remove *any* feature and our commitment to our users (whether they contributed
financially or not). In contrast, private projects are not well-known for
community-led design discussions. So please don't regret your contribution to
the project's development.

Now, because gh-2045 was created for exactly this discussion (and because it
already contains a log of many other relevant perspectives), I'd like to close
this issue. I think the first of your two points is highly relevant to that
conversation--would you mind re-posting it there?

**Comment by sebastien-mignot** [comment]
@jugglinmike I commented on the other ticket.
It's indeed nice that you ask the community about this change you wana make. But if the result of your pondering is that you still remove it, I would still be angry to have paid for it...

Moreover, it's an option. Not even activated by default. Seriously just let the guys who use it live their lives... Those who don't like it don't use it, that's all. Imo it's clear enough in the definition of the option that it can make new errors appear when we update jshint... Put it in capslock in the doc if you think that it's not clear enough.

**Comment by jugglinmike** [comment]
Understood. Thanks for your feedback!
