### ISSUE TITLE
undef: false doesn't work

### ISSUE THREAD

**Issue by rchl** [jshint/jshint#2895]
jshint v2.9.1

Don't understand why undef:false is not preventing W117 from showing up.

.jshintrc:
```
{
  "esversion": 6,
  "undef": false,
  "unused": false
}
```

file.js:
```
'use strict';

class DownloadsToolbar {
  constructor(uiData) {
    this.uiData_ = uiData;
    this.element_ = this.createElement_();
  }

  get element() { return this.element_; }

  focusSearch() { this.element_.querySelector('input').focus(); }

  createElement_() {
    return window.bragi.createTemplate([
      'div', {'class': 'search-controllers'},
      DownloadsToolbar.Templates.searchInput(this.uiData_)
    ]);
  }
};
```

jshint --reporter=unix --verbose file.js
```
file.js:7:1: Use the function form of "use strict". (W097)
file.js:28:2: Unnecessary semicolon. (W032)
file.js:23:12: 'window' is not defined. (W117)
```

**Comment by cattermo** [comment]
I have the same problem with 

.jshintrc
```
"expr": false
```
error message:
```
line 36, col 33, Expected an assignment or function call and instead saw an expression
```

**Comment by nicolo-ribaudo** [comment]
@cattermo You have to use `expr: true`

**Comment by cattermo** [comment]
@nicolo-ribaudo Thank you! 
@rchl Same for you I guess...

**Comment by jugglinmike** [comment]
Thanks for the report! This is the same issue as described in gh-2903, so I'm
going to close it to keep things organized. As I mentioned in that thread, a
short-term workaround would be to formally declare your global variables. Here,
because the global in question is provided by a web browser, you can do this
with [the `browser` environment option](http://jshint.com/docs/options/#browser).
