### ISSUE TITLE
url 404

### ISSUE THREAD

**Issue by gucong3000** [jshint/jshint#2906]
messages.js 
W125: "This line contains non-breaking spaces: http://jshint.com/doc/options/#nonbsp",

http://jshint.com/docs/options/#nonbsp

**Comment by jugglinmike** [comment]
In order to help the team diagnose and fix the problem, an issue report should have the following information:

- Version of JSHint being used
- Input source code (simplified to only contain details necessary to demonstrate the problem)
- Configuration values
- Description of expected behavior
- Description of actual behavior

Could you share that information here?

**Comment by nicolo-ribaudo** [comment]
@jugglinmike The broken link is at https://github.com/jshint/jshint/blob/master/src/messages.js#L208

**Comment by jugglinmike** [comment]
Ah, a documentation issue. Got it.

**Comment by jugglinmike** [comment]
Resolved via 29dd071d66ee16d250ce63c0c4e061b74f7423ac. Thanks for the report!
