### ISSUE TITLE
.jshintrc file ignores everything when { } used

### ISSUE THREAD

**Issue by gbminnock** [jshint/jshint#2912]
Hi, 

I'm wondering if this is correct behavior on windows command line (jshint installed using npm):

I created a .jshintrc file to include warnings I want to ignore: 

```
{
   "-W059": true,
   "-W098": true,
   "-W061": true
}
```

afterwards I wanted to add the warnings back in so I edition my .jshintrc file:

```
{

}
```

However now Im not getting any warnings at all - is this behavior correct? I can start receiving the warnings again if I delete the .jshintrc file. 

Thanks,
Gary

**Comment by jugglinmike** [comment]
I have not been able to reproduce this behavior locally. We'll need more information to diagnose this--would you mind providing the details outlined in [the "Bug Reports" section of the project's contribution guidelines](https://github.com/jshint/jshint/blob/b1c8d5b68e467f9eea830cd7289fb733a1f8131b/CONTRIBUTING.md#bug-reports)?

**Comment by gbminnock** [comment]
sure sorry about that. I was able to get in working correctly when I used the default config mentioned in the source of this project .jshintrc and added what I wanted to exclude.


Details are as follows:

Version of JSHint/node/npm being used:
```
C:\Users\Gary>jshint -v
**jshint v2.8.0**

C:\Users\Gary>npm -v
**3.8.2**

C:\Users\Gary>node -v
**v4.0.0**

```


Input source code (simplified to only contain details necessary to demonstrate the problem)

 files as follows:
test.js
```
function doSomething() {

	for(var a in i) {
		console.log(a);
	}
}
```


Configuration values (.jshint)
`{
}`

Description of expected behavior:
output should be:
> test.js: line 3, col 5, The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.
test.js: line 3, col 18, 'i' is not defined.
test.js: line 1, col 10, 'doSomething' is defined but never used.

Description of actual behavior

> doesn't show any output or any issues


_Note:_

As a test I put everything from the .jshintrc file from the jshint git project into my local file and added what I needed and then it worked.

Thanks,
Gary

**Comment by jugglinmike** [comment]
I think I understand, but I believe this is expected behavior. The three
warnings you are expecting:

> test.js: line 3, col 5, The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.
> test.js: line 3, col 18, 'i' is not defined.
> test.js: line 1, col 10, 'doSomething' is defined but never used.

..are only issued in the presence of certain [JSHint "enforcing
options"](http://jshint.com/docs/options/#enforcing-options). These options are
so named because they cause JSHint to be *more* strict than it is by default.
With running with an empty configuration file, the options are not set, so
JSHint is correctly accepting those patterns.

In the case of an empty configuration file, JSHint should continue to warn
about patterns described via ["relaxing
options"](http://jshint.com/docs/options/#relaxing-options), because those
require explicit configuration to be disabled.

I can confirm that this seems to be working as intended locally by modifying
your example code:

```diff
 function doSomething() {
   for(var a in i) {
     console.log(a);
   }
+  eval("0");
 }
```

Here JSHint issues W061 ("eval can be harmful.") for line 5, even in the
presence of an "empty" configuration file. That's because W061 is enabled by
default, and only silenced with an explicit configuration (`evil: true`, in
case you were curious).

Does that make sense?

**Comment by jugglinmike** [comment]
It's been a week, so I'm assuming my response has clarified things. If there's been a misunderstanding, let me know and we'll re-open!
