### ISSUE TITLE
Feature request: Detect comment column reach

### ISSUE THREAD

**Issue by nattelog** [jshint/jshint#2925]
Hi!

Does JSHint have support for detecting how many columns comments have reached? 

```javascript
/**
 * This is a comment reaching a column number.
 */
function foo() {
  return "bar";
}
```

Can I configure a max column number for the comments and let JSHint report if there are comments reaching beyond the predefined max? This would be useful for sustaining code quality.

BR
Natanael

**Comment by wifiextender** [comment]
> JSHint is a tool that helps to detect errors and potential problems in your JavaScript code

Get some good text editor/IDE and configure it to hint you if some line exceeds the X characters limit.

![sublime-rulers](https://cloud.githubusercontent.com/assets/4725121/15531371/582160b2-225a-11e6-9e20-ba61a71f975e.png)

**Comment by nattelog** [comment]
Yeah, that's a proper solution, definitely. Thanks. I still see a value in JSHint warning me my code and its comments doesn't follow the rules I might have about column limit. Especially if there are several people working on the same code and their IDEs aren't configured with auto-wrapping on that column. 

As you quoted, if JSHint is about detecting errors and potential problems in my code - shouldn't code style also be a part of that problem?

**Comment by wifiextender** [comment]
Hi @nattelog,

No programming/scripting language enforces what programming style you should use. There are recommendations, but the languages themselves won't stop working because of different programming style, e.g "use 4 spaces and not 2/6/8/10/20 spaces".

It's not a program/script error to minify and mangle all the javascript, C, C++ (you name it) language into single line and have it working, thus jshint cannot enforce you what you should and should not do.

Companies, as well group of people contributing to large projects are outlining in the project README.md the guidelines on how you should code, but again they won't reject your commits for exceeding the "spaces" limit.

**Comment by nattelog** [comment]
Ok, I understand. Thank you, @wifiextender. It's just that it would be comfortable having it warn me about style issues. But that's perhaps out of scope for JSHint. Maybe there are other packages that can fix that.

**Comment by wifiextender** [comment]
Hey @nattelog,

There is a **deprecated** [rule] in jshint that allows you to specify the line limit.

```javascript
{
  "maxlen": 30,
}
```

![sc](https://cloud.githubusercontent.com/assets/4725121/15571268/2a46852e-233a-11e6-9624-6acd48a0655c.png)

[rule]: http://jshint.com/docs/options/#maxlen

**Comment by nattelog** [comment]
Oh, interesting @wifiextender! Does it on warn too long text in general or only comments?

**Comment by jugglinmike** [comment]
@nattelog `maxlen` warns about lines exceeding the specified length, regardless of their content. I would advise against using it though, because (as @wifiextender points out) it is deprecated (JSHint's scope is limited to issues of code correctness)

**Comment by nattelog** [comment]
Alright, thanks for the response, @wifiextender and @jugglinmike !
