### ISSUE TITLE
bug in reserved word

### ISSUE THREAD

**Issue by uxitten** [jshint/jshint#2933]
for example

```
var storage={
  set:function(){
   return 1;
  },
  delete:function(){
   return false;
  }
};
```

'delete' is reserved word

**Comment by nicolo-ribaudo** [comment]
If you want JSHint to warn about it, you have to use the `esversion: 3` option.

**Comment by jugglinmike** [comment]
Since ES5, `delete` may be used in that position, and JSHint defaults to linting with ES5 semantics. If you are targeting older environments where that property name would cause problems, then set `esversion: 3` as @nicolo-ribaudo suggests, and JSHint will report the violation. Please let us know if you find otherwise!
