### ISSUE TITLE
Undefined function in strict mode function doesn't create an error

### ISSUE THREAD

**Issue by jensenharris** [jshint/jshint#2939]
Shouldn't this code cause an error? I would expect to be prompted to add a `var` to `b = function() {};`.

```
function a() {
    "use strict";

    b = function() {};
    b();
}

a();
```

**Comment by jugglinmike** [comment]
JSHint exposes the behavior you are looking for, but only for top-level "use
strict" directives. Unfortunately (and [as reported
elsewhere](https://github.com/jshint/jshint/issues/2903)), this implicit
behavior is undesirable because JSHint cannot determine statically whether the
assignment target is defined in the global scope. So although the current
behavior is inconsistent, I expect the "fix" will take the form of removing the
implicit behavior altogether.

If you'd like to explicitly opt-in to this behavior (regardless of language
"mode"), then configure JSHint by setting the "undef" option to "true".

**Comment by jensenharris** [comment]
Thanks!
