### ISSUE TITLE
Why does this line throws 2 errors, 3 warnings?

### ISSUE THREAD

**Issue by AmitMY** [jshint/jshint#2954]
Here is a line of code:
`"group" in scope.$parent && scope.$parent.group.rules.splice(scope.$parent.$index, 1);`

Here are the **errors** & warnings:

> col 29   Missing semicolon.
> col 29   **Expected an identifier and instead saw 'in'.**
> col 29   Expected an assignment or function call and instead saw an expression.
> col 31   **Missing semicolon.**
> col 105  Expected an assignment or function call and instead saw an expression.

Why are the missing semicolons?

Whats wrong with the 'in'?

How to write this line in no-warning/no-error format?

**Comment by AmitMY** [comment]
OK the solution was obvious
```
if("group" in scope.$parent)
                        scope.$parent.group.rules.splice(scope.$parent.$index, 1);
```

**Comment by jugglinmike** [comment]
Although your solution works, you are right to report a bug; JSHint is expected to produce a warning for that input, but not an error. I'm going to leave this issue closed, though, because this has been previously reported as gh-2714. A fix has been submitted (though neglected) at gh-2716. I'll do my best to get that in the next release!

**Comment by AmitMY** [comment]
Yeah, warning and not error makes sence.
Thanks!
