### ISSUE TITLE
Unrecoverable syntax error / Brace

### ISSUE THREAD

**Issue by seraphia** [jshint/jshint#2957]
Hi all,

I encountered a issue when trying to parse the following code snipped:

`function main() {`
`  return 'Hello, World!';`
`}`
`}`
`main();`

Instead of reporting the '}', JSHint dies with an exception 

"Unrecoverable syntax error. (82% scanned)."

Used version: 2.9.2
Default options (also happens in the demo on the website)

**Comment by jugglinmike** [comment]
It is not possible for JSHint to recover from all invalid input because for a
given stream of text, there are many mutually-exclusive interpretations of the
developer's intention. Thats why, when supplied with invalid code, JSHint's
behavior is only loosely-specified. We expect it to report at least one error
(as opposed to a warning) and (in the case of the CLI) exit with a non-zero
exit code. 

If JSHint was behaving this way when supplied with a valid program, that would
be another story. Another valid issue would be if JSHint were truly "dying",
e.g. crashing. As it stands though, the important thing is that JSHint reports
that the input is invalid (and ideally, the location it becomes invalid).
Beyond that, we have to rely on the developer to recognize the solution in
light of their own intentions.

**Comment by jugglinmike** [comment]
In the absence of any further feedback, I'm going to close this report as "Not an issue."
