### ISSUE TITLE
Conditional import not defined in outer scope

### ISSUE THREAD

**Issue by skeggse** [jshint/jshint#2974]
```js
const useModule = /*boolean indicating whether module is needed*/;
if (useModule) import module from './module.js';

if (useModule) {
  module.action();
}
```

If I run jshint against the above snippet with `esnext: true`, it reports `'module' is not defined` for `module.action`. This makes sense, but the syntax is supported in some contexts, including Meteor. Could we add a flag to allow this behavior?

**Comment by skeggse** [comment]
It looks like at around v2.5 this worked, but I'm seeing this behavior as of v2.9.2.

**Comment by jugglinmike** [comment]
With `esnext: true` (or the preferred way to express that: `esversion: 6`), JSHint ought to parse the source text in accordance with ECMAScript 2015. The provided example should actually produce a syntax error, since ImportDeclarations are not supported outside of ModuleItems. I've opened gh-2975 to track the resolution of that bug.

This project is committed to following the ECMA262 specification as closely as possible. If the above is any indication, that is a big enough challenge without also accounting for the various extensions implemented by platforms like Meteor.js.

The solution I would recommend requires two steps: instruct JSHint to ignore the invalid syntax, and also configure JSHint to be aware of the binding that Meteor is creating:

```diff
 // jshint esversion: 6
 /* globals module */
 const useModule = true;
 // jshint ignore:start
 if (useModule) import module from './module.js';
 // jshiint ignore:end

 if (useModule) {
   module.action();
 }
```

This approach will continue to work even when we resolve gh-2975. A solution that automatically recognized the non-standard syntax might be more convenient, but you can read more about JSHint's commitment to language features in [this blog post on the project's website](http://jshint.com/blog/new-lang-features/).

The good news is that [a Meteor developer is slated to make the case for this syntax at the next TC-39 meeting](https://github.com/tc39/agendas/blob/master/2016/07.md), so this may yet be standardized!

**Comment by skeggse** [comment]
Thank you for your consideration :)
