### ISSUE TITLE
Script URL incorrectly

### ISSUE THREAD

**Issue by baivong** [jshint/jshint#2981]
My script doesn't create a new url that is just testing it. I think this shouldn't be a Script URL problem.

```javascript
if (url.protocol === 'javascript:')
```

JSHint version 2.9.1 on [brackets-jshint](https://github.com/cfjedimaster/brackets-jshint)

**Comment by jugglinmike** [comment]
First off, you may supress this warning by [configuring JSHint with `scripturl: true`](http://jshint.com/docs/options/#scripturl).

Clearly there is no danger in the example you've provided, but considering there is an easy way to "opt out," I'm inclinded to keep the behavior as-is. Here's why:

JSHint warns about script-targeted URLs because they are a form of `eval` in the browser. Although there is nothing dangerous about the usage of the string in your example, it is impossible to generally infer how a given string value may be used. The behavior is obviously a little over-agressive, but it's also been around for quite a long time, and we haven't received any other reports about it (to my knowledge). If we can get away with being overly-strict, then I'd rather stick to that approach because it has a higher likelyhood of helping users discover legitamately-dangerous code.

**Comment by jugglinmike** [comment]
In the absence of any further feedback, I'm going to label this as resolved.
