### ISSUE TITLE
"browser: false" strange behaviour

### ISSUE THREAD

**Issue by al-scvorets** [jshint/jshint#3000]
Hi
I use jshint.com on-line (ver 2.9.2 for now) to check my browser apps.
Once i accidentally removed a code line and a trouble happened

```
//var closed = "some evaluated state";   i removed this line by mistake
// ....
if (closed) {   // and now it is window.closed, not my local var!
  // etc., with unexpected result
```

I thought jshint option **'browser:false'** is for this case. Alas it didn't help.
Here is a short example that i tried on-line:

```
/* jshint browser: false */
var a = [window, document, location, name, closed];  // no warnings... why!?
```

Later i found "browser: true" defined in localStorage.
So. Globally (somewhere, i don't bother) defined ["browser: true"]
takes precedence over local explicit definition ["browser: false"] ??
Sounds like a BUG for me.

Best regards, Alexander

**Comment by jugglinmike** [comment]
Thanks for the report! Although the write-up doesn't say this explicitly, I am
inferring from the reference to "localStorage" that you are experiencing this
problem when inputting code on the jshint.com website.

If that's true, then part of the problem is that the application running on the
website enables the `browser` option by default. You can control this behavior
by opening the "Configure" menu (just to the right of the text input element).

Separately, there is the problem of "disabling" an environment option like
`browser`. JSHint is not currently able to do this. This is a problem even
outside of the context of the website. For example, the following code does not
currently produce any warning:

```js
// jshint undef: true
// jshint browser: true
// jshint browser: false
void document;
```

Once enabled, environment options cannot be disabled. This has previously been
reported at gh-1535, so I'm going to mark this report as a duplicate and close.
