### ISSUE TITLE
Declare specific variables as "unused"

### ISSUE THREAD

**Issue by JanisE** [jshint/jshint#3020]
Declaring specific variables as "unused" instead of turning off the hinting of any unused variable altogether (unused: false) would be useful. Similar to how "global" works.

E.g., if I have a function argument that should be there in the interface, but (maybe temporarily) in the particular implementation that argument has no effect and is not used, it gets marked as a potential error.

**Comment by jugglinmike** [comment]
You have a couple options for achieving this result in JSHint today. For an
unused binding named `foo`, you can silence warnings by:

1. declaring the variable as `exported` (e.g. `/* exported foo */`)
2. applying the `void` operator to the binding (e.g. `void foo;`)

The first option will only work for top-level unused bindings, so it may not be
applicable in all cases (besides also being semantically inaccurate). I
personally prefer using the second option because it is a more explicit signal.
The `void` statement tells the reader, "yes, we recognize that this binding is
unused," without requiring additional knowledge of JSHint's features
(potentially hidden away in some separate `.jshintrc` file).

That said, neither approach causes JSHint to *enforce* that the binding go
unused. That doesn't sound like a requirement from your use case, though, so
this is probably fine. Does that work for you?

**Comment by JanisE** [comment]
Sorry for not replying!

I'm not sure what the particular case was when I wrote the post, but here is an example I can think of right now:

```
/* global jQuery, console */
jQuery.each([52, 97], function (index, value)
{
	console.log(index);
});
```
JSHint gives me: `tet.js: line 2, col 40, 'value' is defined but never used.`

How should I include `void` there? Tried in code, in comments in a couple of ways, but that didn't help.

**Comment by JanisE** [comment]
Oh, I got it. I have to write `void value` as the first thing in the function body. It worked, thanks!

I'm not that familiar with what is void's (original?) meaning, but if this seems like a natural use of `void` to you, then probably it's a good solution.

Thank you!

**Comment by jugglinmike** [comment]
Sure thing! I'd like to point out that the behavior of jQuery's `each` method
is not dependent on the number of formal parameters in the provided predicate
function. So for the example you've provided here, you could also simply omit
the second parameter altogether.

Of course, there are other libraries that *do* respond to function length.
Hopefully they do so in a way where the "extra" parameter(s) are strictly
necessary, but if they don't, `void` is a good choice for this (although a
patch to the library in question might be a good idea, too!)
