### ISSUE TITLE
change "Possible strict violation" to a clearer message

### ISSUE THREAD

**Issue by a7madgamal** [jshint/jshint#3033]
I think this message is very ambiguous.
Is it for a specific error or for a range of errors? and if it was for a specific one, what does it mean or what should I do to fix it?

this issue is concerned with the message itself, regardless of how to fix or ignore it.

jshint v2.9.1

```
{
  "undef": true,
  "unused": true,
  "mocha": true,
  "node": true,
  "browser": true,
  "indent": 2,
  "eqeqeq": true,
  "maxlen": 130,
  "multistr": true,
  "trailing": true,
  "latedef": true,
  "curly": true
}
```

**Comment by jugglinmike** [comment]
This warning is intended to prevent bugs due to confusion about the `this`
binding. While any strict mode function that contains `this` is susceptible to
such bugs, the warning is limited to function declarations because those are
most likely to be invoked as functions (versus as methods or via
`Function.prototype.apply`). The warning can be disabled via the `validthis`
option (declared as an in-line directive) or by targeted configuration (via
`-W040`).

That said, your point is well-taken. This one is a bit tricky to explain
succinctly, but I'll try. What do you think of:

> The `this` value of strict mode function declarations will be undefined when
> invoked as a function.

**Comment by a7madgamal** [comment]
yeah looks much better

**Comment by jugglinmike** [comment]
Great! Looking at this with fresh eyes, I realized that the message confuses subject and object. I've submitted a modified version at gh-3052.

**Comment by jugglinmike** [comment]
Resolved via gh-3052.
