### ISSUE TITLE
Add 'Map' to Node globals

### ISSUE THREAD

**Issue by jamesshore** [jshint/jshint#3040]
jshint@2.9.3: When using the 'node' option, "Map" should be in the list of global variables.

**Comment by jugglinmike** [comment]
While `Map` may be globally defined in the latest version of Node.js, we have
to be sensitive to users who (for whatever reason) are using older versions of
that platform. In order to avoid conflating platform versions with language
features, JSHint defines a separate configuration option, `esversion`. The
following configuration should produce the behavior you are looking for:

```json
{
  "node": true,
  "esversion": 6
}
```
