### ISSUE TITLE
unused function parameter (is defined but never used)

### ISSUE THREAD

**Issue by spaceone** [jshint/jshint#3059]
Hey :) Feature Request:

$ jshint --version
jshint v2.9.3

Take the following code as example:
```
function(foo, bar) {
    var baz;
    return bar;
}
```

jshint reports:
'foo' is defined but never used.
'baz' is defined but never used.

Would it be possible to split these issues into 2 errors/messages. I would like to ignore every function parameter which is not used because I have many dojo API's/interfaces to implement but still want to detect unused variables like 'baz'.

**Comment by jugglinmike** [comment]
Hi there. I believe JSHint already has you covered; here's a complete example:

```js
// jshint unused: true
void function(foo, bar) {
    var baz;
    return bar;
}
```

Entered on [JSHint.com](http://jshint.com) (currently running version 2.9.4), this produces just one warning:

>     3 'baz' is defined but never used.

We don't expect the warning about `foo` being unused because `bar` *is* used, which makes providing a binding for the first parameter necessary.

Note that I had to modify your example in order to make the input valid JavaScript. I expect that an important detail may have been lost when you created a reduced example case for us, so I'll wait for confirmation from you before closing this issue.

In particular, it sounds like maybe you want to silence warnings for parameters that are truly unused. If that is the case, you can specify `unused: vars` (see [the documentation on `unused` for more information](http://jshint.com/docs/options/#unused)). Although in that case, I would encourage you to just omit the unused parameters entirely--unless the library you are using operates on function arity (which is kind of suspect), you can still conform to the API without defining unused parameters.

**Comment by spaceone** [comment]
Thank you very much!
