### ISSUE TITLE
Add a new "chai" environment option

### ISSUE THREAD

**Issue by AMorgaut** [jshint/jshint#3070]
JSHint is already providing unit test related environment options such as:

* `jasmine`
* `mocha`
* and `qunit`

[chai](http://chaijs.com/), is often used with mocha and provides a very nice [expect/should](http://chaijs.com/api/bdd/) BDD oriented API

If it was just about declaring few globals, there would be no big need of such `chai` option, but... this API lets the user write things like
 
```js
expect(foo).to.exist
```

It use `accessor properties` (cf [ES5 Property Attributes](http://www.ecma-international.org/ecma-262/5.1/#sec-8.6.1)) and JSLint/JSHint/ESLint will make no difference with data properties and complain:

> 	Expected an assignment or function call and instead saw an expression.

Currently proposed solutions include activating the options `-W024` and/or `expr:true`, but they would be global to at least the file and won't raise warnings where they really is some errors

Some then also used some workaround making it possible to write
```js
expect(foo).to.exist()
```
or worst
```js
expect(foo).toExist()
```
(ex: "dirtychai")

But you are then loosing the whole point of this API which is to be as minimalist, and as near to test case meaning as possible.

I thought that the Linter might allow a more atomic `expr` option (ex: `expr: 'accessor'`) to not raise warnings when expressions end with an "accessor property" instead of a method call. It can be interesting in some very specific  situations (ex: forced singleton instantiation). Should I create a feature request for that?

Still, here again such option would apply to the whole file when we might only want it for the chai API.
I think that, due to the `chai` popularity and to current support of the mentioned test related environments, it would be very legitimate to provide a dedicated `chai` option

You can get more information on that topic with [my last comment](https://github.com/chaijs/chai/issues/41#issuecomment-260652126) in this thread: https://github.com/chaijs/chai/issues/41

**Comment by jugglinmike** [comment]
Thanks for the thoughtful report!

We're trying to move away from supporting library-specific "environment"
options in JSHint "core". JavaScript libraries come and go, and even the
well-established ones like Chai are subject to change over time. When their API
changes, it puts JSHint in an awkward position of having to support multiple
versions concurrently. The other libraries you've referenced are effectively
"grandfathered in,"--we're taking the maintenance burden to honor commitments
made before this change in policy.

Your idea about accessor properties may be a path forward, though. There is a
larger issue underlying the use of Chai's `expect` API--namely, that a typo in
a property name will produce false positives. While my reluctance to implement
any Chai-specific solution stands, there may be a case for a user-defined list
of accessor property names.

For instance:

```js
expect(foo).to.exist;
```

Currently produces:

>     line 1, col 16, Expected an assignment or function call and instead saw an expression.

...but maybe this could be permitted with configuration like:

```
// jshint.accessors exist
expect(foo).to.exist;
```

It's a pretty imprecise solution for static analysis, though.
`expect(foo).to[varWithValueExist]` would continue to trigger the warning, and
`expect(foo).TO.exist` would not. It's not clear if the edges of a feature like
this would give users false confidence about its ability (or worse yet, promote
bugs itself!).

Personally, I'm not very motivated to support this because I have a hard time
working with code bases that depend on side effects in accessor properties. (I
use Chai but avoid that API.) In my experience, that is itself a bad practice,
so in some ways, making it slightly safer is potentially worse than not
supporting it at all. Open to suggestion, though!

**Comment by AMorgaut** [comment]
I understand the point about supporting library specific options

I still think that it is interesting to have linters aware of accessor properties and probably give a warning about their potential abuses (I agree they can lead to very bad/confusing patterns) and still tolerate them in some very specific situations.

By default I think as I said that such usage (as singleton forced instantiation)  should be very specific and would deserve a comment that could relax the linter at the line level

Then there is APIs like chai that I still found legitimate because we write almost only what is required and prevent noise. So maybe could we, as for globals, external lib, give a list of accessor attributes to tolerate at the folder level, which would only contains test files, via the .jshintrc file

**Comment by jugglinmike** [comment]
We're part-way there: JSHint already supports a mechanism for extending
configurations: [the `extends` option](http://jshint.com/docs/cli/). If JSHint
also supported the `accessors` feature, then a project like Chai could provide
a minimal JSHint configuration file, and consumers could use `extends` to bring
it in to their own configuration.

But now we are getting in to discussing feature that is altogether separate
from the purpose of the original feature request. To help keep this
discoverable, I'm going to close this in favor of a new issue: gh-3086.

**Comment by sebs** [comment]
Hint: I was looking for  a way to not get warnings for JSHINT + expect, but not use JShint exempts. Closed on 8th Jan? Is there a piece of documentation about it?
