### ISSUE TITLE
W030 Warning

### ISSUE THREAD

**Issue by vitalijm** [jshint/jshint#3078]
```
			    for (var i = 0; i < varsL; i++) {
			      obj.v[i]; // W030 - Expected an assignment or function call and instead saw an expression.at line 356 col 19
			      obj.s = obj.s.replace('==' + i + '==', obj.v[i]);
			    }
```

Why here i saw this code warning?

**Comment by jugglinmike** [comment]
JSHint is warning about that statement because it is an expression that typically does not have a side-effect. In many cases, this is a sign of a programming error--the author often intends to use the result of the expression as part of some other operation (e.g. assigning a value to a binding or invoking a function).

In your example, it's certainly possible that `obj.v` is an object with one or more accessor properties, but this is not the common case. You can allow that pattern with [the `expr` option](http://jshint.com/docs/options/#expr), either for your whole project (by enabling it in a `.jshintrc` file) or for that line (by enabling it with an in-line directive)--[see the project documentation for more details on setting linting options](http://jshint.com/docs/).

Hope this helps!
