### ISSUE TITLE
Tolerate using not defined variables when it's determined that the variables exists at run time

### ISSUE THREAD

**Issue by MoritzKn** [jshint/jshint#3089]
I think even if `undef` is `true`, variables that are not (in the current file) defined should be tolerated when the programmer checks that the variables exists at run time. A example for this would be:
```js
if (typeof foo !== 'undefined') {
	foo = 'bar';
}
```
Concrete this would mean the use of not defined variable should be tolerated if any of the enclosing `if` statements contain one of these checks:
* `typeof $variable === $type` 
* `typeof $variable == $type` 
* `typeof $variable !== 'undefined'`
* `typeof $variable != 'undefined'`
* `$variable != null`
* `$variable !== undefined`
* `$variable != undefined`
* `$variable`
* `!!$variable`

where `$foo` is the name of the variable and `$type` any string but `'undefined'`.

**Open questions for me are:**
* What when the type not a string literal but an expression?
* Is `$variable !== undefined` save? In some older JS versions (I think ES4 and ES5 without strict mode) `undefined` is a variable that can be reassigned.
* How difficulty is it to check if a `if` statement contains a check like the above if the `if` statement contains a non trivial expression?

**Comment by jugglinmike** [comment]
Like any new feature, implementing this functionality would increase the
complexity of the code base. This is a trade-off we usually accept because we
don't value simplicity for its own sake; we generally prefer a more helpful
tool over a simpler one.

However, the added complexity for this behavior is harder to justify because it
wouldn't make JSHint more helpful consistently. The suggested heuristic isn't
quite predictable for an end-user because it would fail to recognize all sorts
of patterns for checking binding existence:

    "undefined" === typeof $variable
    $anotherVariable = "undefined", typeof $variable === $anotherVariable
    $anotherVariable = typeof $variable, $anotherVariable === "undefined"

The first half of the suggested checks would probably suffice for many
scenarios. (The latter half of the suggested checks are actually inappropriate,
as they all produce errors in contexts where a binding for `$variable` does not
exist.) That said, implementing this would still increase the complexity of the
code base.

One of our criteria for linting behavior is that it be consistent and
predictable. For a dynamic, interpreted language like JavaScript, this
requirement can sometimes be a real limit to the kind of assurances we can
provide through static analysis. But when we cannot address a problem
completely, we risk causing confusion for developers, and that is exactly what
the project was created to mitigate.

**Comment by jugglinmike** [comment]
Generally, the best practice for detecting globals is to qualify the reference
as a property access of the global object. In a web browser, that could look
like:

```js
if (typeof window.foo !== "undefined") {
  window.foo = "bar";
}
```

Hope that helps!

**Comment by MoritzKn** [comment]
I can understand this decision; thanks for the comprehensive explanation.

**Comment by jugglinmike** [comment]
Sure thing!
