### ISSUE TITLE
how can i use jshint in .cshtml?

### ISSUE THREAD

**Issue by SaravananArunagiri** [jshint/jshint#3112]
```
 $.ajax({
                url: '@Url.Action("PartialDashboard","Home")',
                type: "GET",
                success: function (data) {
                    $("#partialDashboard").html(data)    --> here wants to validate semicolon
                } 
            })
```

The above code in my .cshtml <script>. How can i use jshint in .cshtml file. Now i use the online version validate and again copy the code into file. **# Any possible option to validate in visual studio 2015 ?**

**Comment by jugglinmike** [comment]
I'm not familiar with `.cshtml`, but the `--extra-ext` CLI option will let you
configure JSHint to analyze non-JavaScript files. Since this sounds like a case
where the script is embedded within markup, the `--extract` option may also be
relevant. You can read more about the command-line interface and its flags in
the dedicated page in the project documentation:

http://jshint.com/docs/cli/

As for editor integration, the following JSHint documentation page has
references to various plugins (including Visual Studio):

http://jshint.com/install/

Hope this helps!
