### ISSUE TITLE
Documentation refer to JSCS project, which is deprecated

### ISSUE THREAD

**Issue by lucile-sticky** [jshint/jshint#3121]
Hello!

## Problem

I was reading the documentation, and each time an option is related to code formatting, description says it's deprecated and we need to check out the [JSCS project](https://github.com/jscs-dev/node-jscs).

Unfortunately, this project is deprecated:
> JavaScript Code Style checker (deprecated)
-- https://github.com/jscs-dev/node-jscs

> JSCS has merged with ESLint!
-- http://jscs.info/

> ### JSCS — end of the line
> 
> JSCS 3.0 is finally out, and we are both very excited and a little sad. Excited because this new version is something that we’ve worked very hard on, and sad because this will be the last version of JSCS.
-- https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2

## Question
Do you think update the documentation to make it point on the [ESLint project](http://eslint.org) is a good idea?

**Comment by jugglinmike** [comment]
The term "deprecated" is somewhat of a misnomer in this context because it
indicates intent of future removal. Thankfully, that's not the case here, as
noted in the blog post you referenced:

> The JSCS repository will be left in place, so you are free to fork it and
> otherwise use the code.

In releasing version 3.0, the original JSCS left us with a powerful, stable
piece of software. Even today, it holds up as a code style enforcement utility,
which is exactly what JSHint users are looking for. ESLint has a much larger
scope and isn't always appropriate for use alongside JSHint.

It might be nice to update JSCS's documentation instead--to clearly indicate
that it is not actively maintained, and ideally to offer maintenance privileges
to folks who might be interested. @hzoo do you have any thoughts about that?

**Comment by jugglinmike** [comment]
The term "deprecated" is somewhat of a misnomer in this context because it
indicates intent of future removal. Thankfully, that's not the case here, as
noted in the blog post you referenced:

> The JSCS repository will be left in place, so you are free to fork it and
> otherwise use the code.

In releasing version 3.0, the original JSCS left us with a powerful, stable
piece of software. Even today, it holds up as a code style enforcement utility,
which is exactly what JSHint users are looking for. ESLint has a much larger
scope and isn't always appropriate for use alongside JSHint.

It might be nice to update JSCS's documentation instead--to clearly indicate
that it is not actively maintained, and ideally to offer maintenance privileges
to folks who might be interested. @hzoo do you have any thoughts about that?

**Comment by rayfoss** [comment]
The jshint documentation on the "indent" option tells us to us JSCS. Then the JSCS ReadMe.md tells us to us JSHint... which one is it?

From what I gather you are saying the JSCS readme is incorrect and you should not use JSHint for code style and instead use the deprecated JSCS?

https://github.com/jscs-dev/node-jscs

**Comment by hzoo** [comment]
> The jshint documentation on the "indent" option tells us to us JSCS. Then the JSCS ReadMe.md tells us to use JSHint... which one is it?

JSCS (JavaScript Code Style checker) was created solely for code style so you can use it in addition to JSHint (focused on errors, etc and was doing style checks earlier). That's why the projects partnered together to focus on different things. JSCS "merged" in terms of moving the teams over to ESLint since the JSCS wanted to join forces with ESLint instead. Deprecated might not be the best word, it's just unmaintained at the moment but it works fine.

**Comment by jugglinmike** [comment]
> I'l change the wording in the repo to say "unmaintained"

Thanks, Henry!
