### ISSUE TITLE
[Feature Request] Error/Warning return error code

### ISSUE THREAD

**Issue by branpar** [jshint/jshint#3145]
Hi,

JSHint is a great tool to see code issues as they happen during development but I would also like to use this in the deployment pipeline to lint code going out to production. If there's a JS error that JSHint finds, in this instance, I'd like for it to generate a non-zero error code so the deployment process stops.

Additionally I'd like the ability to treat warnings as errors (a configuration option) so that in the future we also can't deploy code to production if warnings are generated. 

Is this something that could be added to the roadmap?

Thanks!

**Comment by jugglinmike** [comment]
> If there's a JS error that JSHint finds, in this instance, I'd like for it to
> generate a non-zero error code so the deployment process stops.

This has been the intended behave of the JSHint CLI since its creation. There
may be some larger issue at play here; some more information will help us find
the problem:

- What operating system are you using?
- What version of Node.js/npm are you using?
- How did you install JSHint?
- How are you invoking the program? i.e. What shell are you using, and what are
  you typing into it?

Here's a demonstration on my system (running GNU/Linux with bash):

    $ jshint  --version
    jshint v2.9.5
    $ jshint  --verbose -
    var enum;
    stdin: line 1, col 5, Expected an identifier and instead saw 'enum' (a reserved word). (W024)

    1 error
    $ echo $?
    2

> Additionally I'd like the ability to treat warnings as errors (a
> configuration option) so that in the future we also can't deploy code to
> production if warnings are generated.

This is the default behavior.

**Comment by branpar** [comment]
Thank you for the response. 

What operating system are you using?
Windows 7 Enterprise

What version of Node.js/npm are you using?
Node: 6.6.0
NPM: 3.10.9

How did you install JSHint?
It's part of the package,json, so it's installed as part of the `npm install` that's first run.

How are you invoking the program? i.e. What shell are you using, and what are
you typing into it?
I run it via Windows CMD or through our build process which I believe is just a Windows CMD.  It's initiated as part of a gulp task. It has it's own task and is also run in a series of tasks, let's say for our production build process.

I'm including the output of one of our repositories when I run JSHint on it.

```
C:\WebTeam1\CDN\common>gulp jshint
[07:40:02] Using gulpfile C:\WebTeam1\CDN\common\gulpfile.js
[07:40:02] Starting 'jshint'...


scripts\modules\dropdown-service.js
  line 74  col 13  'timeout' is defined but never used.
  line 89  col 13  'timeout' is defined but never used.

  ‼  2 warnings


scripts\modules\header.js
  line 706  col 17  'timeout' is defined but never used.
  line 716  col 17  'timeout' is defined but never used.
  line 728  col 13  'timeout' is defined but never used.

  ‼  3 warnings


scripts\modules\validation.js
  line 143  col 25  Unexpected escaped character '<' in regular expression.
  line 230  col 22  'k' is defined but never used.
  line 380  col 17  Function declarations should not be placed in blocks. Use a function expression
or move the statement to the top of the outer function.
  line 407  col 17  Function declarations should not be placed in blocks. Use a function expression
or move the statement to the top of the outer function.

  ‼  4 warnings

[07:40:03] Finished 'jshint' after 1.49 s

C:\WebTeam1\CDN\common>
```

We can see it found warnings but didn't return any sort of error code. I'm also including the gulp task:

```
const gulp = require('gulp'),
      config = require('../config'),
      jshint = require('gulp-jshint');

gulp.task('jshint', function () {
    return gulp.src(config.tasks.jshint.src)
      .pipe(jshint(config.tasks.jshint.settings))
      .pipe(jshint.reporter('jshint-stylish'));
});
```

And the configuration settings I have overwritten to check for more items:

```
      "settings": {
        "curly":  true,
        "eqeqeq": true,
        "esversion": 6,
        "unused": "vars",
        "varstmt": true,
        "latedef": "nofunc"
      }
```

I wouldn't want it to always kill the process (say, for a watched task I want it to be able to alert me of these errors on the fly and keep going) but if I'm attempting to deploy to production and I get an error I want it to kill the process and not allow it to go out. The warnings treated as errors is also desirable for the same effect.

**Comment by jugglinmike** [comment]
Thanks for the information. Your project depends on JSHint indirectly, through [the `gulp-jshint` module](https://www.npmjs.com/package/gulp-jshint). See this line:

>     jshint = require('gulp-jshint');

JSHint is not itself aware of the Gulp build tool; `gulp-jshint` is maintained by another group of developers in order to integrate the two projects. Details concerning the way Gulp and JSHint interact (such as how the latter effects the exit status of the former, as in your original report) are most likely related to that project.

The use case you have described is very common, so this may be a simple matter of configuration. I recommend reading up on the documentation on the `gulp-jshint` project and potentially filing a support request there.

**Comment by jugglinmike** [comment]
It's been a couple months since we've heard from you, so I'm assuming that my previous comment cleared up the problem. Drop us a line if you find you're having problems with the JSHint module.
