### ISSUE TITLE
Function-scoped "use strict" doesn't seem to apply

### ISSUE THREAD

**Issue by whitlockjc** [jshint/jshint#3204]
I apologize if I'm doing things wrong but I've looked at the docs, searched the issue tracker and elsewhere but I'm still not sure what is up.  Whenever I use function-scoped strict mode enablement, JSHint doesn't seem to catch the errors/warnings unless I set `globalstrict` or `strict`. 
 Is there no way to have strict mode checking enabled conditionally based on the existence of the enablement statement?

Here is my example script:

```js
(function () {
  'use strict';

  // Strict mode compliant
  // var name = 'JSHint';

  // Not valid in strict mode since it's attempting to assign to an undeclared variable
  name = 'JSHint';

  // Not valid in strict mode since it's attempting to use an undeclared variable
  context.setVariable('NAME', name);
})();
```

And here is my `.jshintrc`:

```json
{
  "globals": {
    "context": true
  },
  "-W034": true
}
```

When I run `jshint my-file.js`, I do not get any errors or warnings output while I would had expected the following:

```
my-file.js: line 8, col 3, 'name' is not defined.
my-file.js: line 10, col 31, 'name' is not defined.

2 errors
```

Am I doing something wrong?  I'm using `jshint v2.9.5`.

**Note:** I realize that the test above is somewhat convoluted but this is how JavaScript snippets are written by customers and then invoked by our runtime.  This is not my code.  ;)

**Comment by jugglinmike** [comment]
Short answer: The behavior you're experiencing is expected. Enable [the `undef` option](http://jshint.com/docs/options/#undef) to cause JSHint to report references to undefined bindings.

Long answer:

While strict mode code produces an error when assigning to variables that have not been declared, this is a runtime error. It cannot be detected statically because the presence of global bindings can't be known statically. A couple examples:

```js
'use strict';
global['f' + 'o' + 'o'] = null;
(0,eval)('var bar;');

foo = 0;
bar = 0;
```

It's definitely possible for JSHint to make educated guesses: that's what the `undef` option enables. But since this can only ever be an approximation of the runtime behavior in strict mode, we require users to explicitly opt-in.

Related to your code sample in particular, note that [browser environments provide a global binding name "name"](https://developer.mozilla.org/en-US/docs/Web/API/Window/name). In recognition of that, JSHint would not report an warning even when `undef` is set... If [linting code for the `browser` environment](http://jshint.com/docs/options/#browser), this is. Based on the information you've shared, this doesn't look to be relevant for your case, but I wanted to point that out in case anyone else stumbles on this discussion thread in the future.

**Comment by whitlockjc** [comment]
Fair enough, thanks for taking the time.

**Comment by jugglinmike** [comment]
Sure thing.
