### ISSUE TITLE
List outer scoped variables of W083

### ISSUE THREAD

**Issue by flaviojs** [jshint/jshint#3211]
I was getting W083 with this code:
```
$.ajax({
  contentType: "application/json; charset=utf-8",
  type: "GET",
  url: api("/machines"),
  beforeSend: function() { $('#machines-spinner').removeClass('hidden'); },
  cache: false,
}).done(function (machines) {
  if (machines.length > 0) {
    var $machines = $('#machines').html('');
    for (var i = 0; i < machines.length; ++i) {
      var html = $('#template-machine').html().replace(/{{\w*}}/g, function (x) { // W083
        if (x === '{{id}}') return machines[i].id;
        if (x === '{{name}}') return machines[i].name;
        if (x === '{{targetoee}}') return machines[i].targetoee;
        if (x === '{{code}}') return machines[i].code;
        return x;
      });
      $machines.append($(html));
    }
  }
  else {
    $('#machines').text('No data.');
  }
  $('#machines-spinner').addClass('hidden');
}).fail(...);
```

I tried wrapping the code but it didn't remove the error:
```
...
      (function (machines, i, $machines) { // W083
        var html = $('#template-machine').html().replace(/{{\w*}}/g, function (x) {
          if (x === '{{id}}') return machines[i].id;
          if (x === '{{name}}') return machines[i].name
          if (x === '{{targetoee}}') return machines[i].targetoee
          if (x === '{{code}}') return machines[i].code;
          return x;
        });
        $machines.append($(html));
      })(machines, i, $machines);
...
```

Not knowing what else to try I gave up and added the `loopfunc` option.

I still don't know which "outer scoped variable" he was referring to.
I'd like jshint to list the offending outer scoped variable(s) with W086, even if it's only in `--verbose` mode.

**Comment by jugglinmike** [comment]
Hi there, Flávio, thanks for the report! The problem is the reference to the `$` function. There are two ways to resolve this:

1. Include `$` in the parameters of the immediately-invoked function expression (and the corresponding argument list)
2. Configure JSHint to recognize `$` as an immutable global binding (i.e. `$:  false`). JSHint should correctly recognize that there is no risk for confusion when the reference cannot be modified

That said, I agree that debugging this warning is kind of difficult without the list of bindings. Implementing your request shouldn't require very much code. I'd be happy to help you write a patch--do you have any interest?

**Comment by flaviojs** [comment]
I was expecting the `jquery` option to handle `$` since it defines it, seems I was wrong.

I'll try to make a pull request.

**Comment by flaviojs** [comment]
Note that the current master (a11d6310c5448304d56be081dc02b4c2a1ff7377) doesn't complain about `$` with the `jquery` option, but the current jshint in npm does (v2.9.5).
