### ISSUE TITLE
Illegal 'use strict' directive in function with non-simple parameter list

### ISSUE THREAD

**Issue by dhilt** [jshint/jshint#3212]
Not sure if it's **Bug report** or **Feature request**, but I have following situation. 

**Repro**

1. My function has a default parameter and 'strict mode' directive:

```
function runGridTest(scrollSettings, run, options = {}) {
  'use strict';
  // ...
}
```

2. My .jshintrc has enabled 'strict' option: `"strict": true`. Also it has `"browser": true`.

3. I run jshint over ./test folder and then Karma Chrome tests via npm script

```
"test": "jshint --verbose test && karma start test/config/karma.conf.js"
```

**Result**

Jshint passes successfully, but Karma fails with 

> SyntaxError: Illegal 'use strict' directive in function with non-simple parameter list

And there are a bunch of similar cases described on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Strict_Non_Simple_Params).

**My expectaion**

Jshint could throw appropriate warning. Maybe it would be a good idea to prohibit non-simple parameters if `strict` and `browser` options are set to `true`?

**Comment by jugglinmike** [comment]
This is a known issue. (By the way: it isn't limited to browser code--it's part of JavaScript itself.) [We've resolved it](https://github.com/jshint/jshint/commit/31462b2eea23bace4c4a1d197d29d912abce5dc1) in [the feature branch for the next minor release](https://github.com/jshint/jshint/tree/v2.10.0). Since that's not yet available, I'll keep this report open and use the "has PR" tag to communicate that the fix is on the way.

Thanks for taking the time to report this!

**Comment by cloudrac3r** [comment]
This is still an issue using the checker interface on https://jshint.com.

Minimal example:

```
function a(b = 0) {
  "use strict";
}
a();
```

With ES6 features turned on in the configuration, JSHint does not report any problems, but in actual fact this code will not run:

    SyntaxError: "use strict" not allowed in function with default parameter

**Comment by jugglinmike** [comment]
The restriction you're referencing was introduced in ES2016, so if you're linting your code with the `esversion` set to `2015` (or `6`), then JSHint will not report an error because this was not an error in that revision of the language. If you set `esversion` to `2016` (or `7`) or any later value, then you'll see the error you expect:

    $ echo '/* jshint esversion: 6 */ function a(b=0) { "use strict"; }' | ./bin/jshint --verbose -
    $ echo '/* jshint esversion: 7 */ function a(b=0) { "use strict"; }' | ./bin/jshint --verbose -
    stdin: line 1, col 45, Functions defined outside of strict mode with non-simple parameter lists may not enable strict mode. (E065)
    
    1 error

**Comment by Simbiat** [comment]
I know this is an old thread, but there is also a contradiction in behavior: if you place `use strict` inside the function with non-simple parameters, there will be an error notifying about it, yes, but if you do not, you still get:
`Missing "use strict"; statement.`
Also ES allows placing `use strict` before the functions with non-simple parameters, but then JSHint also shows this:
`Expected an assignment or function call and instead saw an expression.`

**Comment by jugglinmike** [comment]
> I know this is an old thread, but there is also a contradiction in behavior: if you place `use strict` inside the function with non-simple parameters, there will be an error notifying about it, yes, but if you do not, you still get:
> `Missing "use strict"; statement.`

This is expected behavior, but it's configurable. If you'd like to modify
JSHint's requirements for strict mode, check out [the option named "strict"](https://jshint.com/docs/options/#strict)

> Also ES allows placing `use strict` before the functions with non-simple parameters, but then JSHint also shows this:
> `Expected an assignment or function call and instead saw an expression.`

This sounds like an unrelated problem. Can you share some example code?

Sight unseen, I'd guess that you may be attempting to enable strict mode in a
statement that isn't the first in the program or the first in a function body.
The "use strict" directive only works in those positions; if it follows any
other statement, it won't enable strict mode (and JSHint will issue the warning
you've reported as a way to communicate that it has no effect).

**Comment by Simbiat** [comment]
@jugglinmike I'm trying to do this:
```javascript
//Timer to show remaining or elapsed time
'use strict';
function timer(target, increase = true) {
    setInterval(function() {
        if (parseInt(target.innerHTML) > 0) {
            if (increase === true) {
                target.innerHTML = parseInt(target.innerHTML) + 1;
            } else {
                target.innerHTML = parseInt(target.innerHTML) - 1;
            }
        }
    }, 1000);
}
```

If I place `use strict` at the top of the file, I get 
`Use the function form of "use strict". (W097)`
So.. I guess I need to use `globalstrict` option here and this is an expected behavior.

**Comment by jugglinmike** [comment]
Yup! Or, if you prefer, you can wrap the whole file in an immediately-invoked function expression which includes the directive.
