### ISSUE TITLE
Allow object destructuring assignment

### ISSUE THREAD

**Issue by xqin** [jshint/jshint#3218]
```
$ cat 1.js
'use strict'

let a = {x: 1, y: 2}

let b = {...a, c: 3}

console.log(b)
$ cat .jshintrc
{
  "asi": true,
  "esversion": 6,
  "strict": true,
  "node": true,
  "undef": true,
  "unused": true
}

$ jshint 1.js
1.js: line 5, col 10, Expected '}' to match '{' from line 5 and instead saw '...'.
1.js: line 5, col 13, Missing semicolon.
1.js: line 5, col 16, Expected an assignment or function call and instead saw an expression.
1.js: line 5, col 17, Missing semicolon.
1.js: line 5, col 16, Unrecoverable syntax error. (62% scanned).

5 errors
$ jshint --version
jshint v2.9.5
```

![image](https://user-images.githubusercontent.com/1265888/33299248-b3b462b6-d425-11e7-84bd-a88fc915a474.png)

expected： no error

**Comment by jugglinmike** [comment]
Thanks for the detailed report! The technical name of the language feature you are describing is "object spread properties" and "object rest properties". Since we already have a tracking issue for the feature request (see gh-2991), I'm going to close this report as a duplicate.

Good news, though: support has been implemented on a feature branch and is expected for the next minor release of JSHint!
