### ISSUE TITLE
Exported hint seems to have no effect?

### ISSUE THREAD

**Issue by JosefWN** [jshint/jshint#3223]
```javascript
/*exported plt, gte, pgte, points, sqToDisc, plot, group*/
function plt() {
 // ...
}
// ...
```

Doesn't give a warning, but it shows plt as unused?

**Comment by jugglinmike** [comment]
I can't reproduce your problem based on the reported information. I suspect that you may have some additional configuration that is relevant here since the source you provided does not explicitly enable the `unused` option (which is disabled by default). Even after enabling that, I'm not able to trigger the reported behavior:

    $ jshint -
    // jshint unused: true
    /*exported plt, gte, pgte, points, sqToDisc, plot, group*/
    function plt() {
     // ...
    }
    // ...

    $ echo $?
    0
    $ jshint --version
    jshint v2.9.5
    $ node --version
    v8.3.0
    $ npm --version
    5.5.1

[The project's contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md) have more detail about the information we need to be able to help.
