### ISSUE TITLE
Variable outside for loop bug

### ISSUE THREAD

**Issue by nemanjan00** [jshint/jshint#3236]
Hi, this is my code: 

```javascript
workers = [];

for(i = 0; i < settings.botSettings.threads.value; i++){
		let worker = child_process.fork(path.join(process.cwd(), "./src/thread"));

		worker.send({
				type: "init",
				data: {
						port: port
				}
		});

		worker.on("message", function(message){
				if(message.type == "log"){
						console.log(message.data);
				}
		});

		workers.push(worker);
}
```

And jshint is giving me ``Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.`` warning for this line: 

```javascript
worker.on("message", function(message){
```
I am not using anything outside that function in that line, what is the problem?

**Comment by jugglinmike** [comment]
> I am not using anything outside that function in that line, what is the
> problem?

The error is referring to the offending function, not to the variable
reference. (Good news: in the next release of JSHint, the warning message will
include a list of all the offending bindings.)

In your case, the offending reference is `console`. I think we'd both agree
that using `console` within a loop isn't particularly dangerous, but to JSHint,
that is just another variable that might change with each iteration.

JSHint will *not* issue that warning if it recognizes the binding is immutable
(since in that case, there is definitely no danger in the closure's reference).
That means the best way to silence the error would be to configure JSHint to
treat `console` as immutable. You can do this via an in-line directive via the
following JavaScript comment:

    /* globals console: false */

...or you can add the configuration to your `.jshintrc` file.

In either case, this will also cause JSHint to report a warning if any code
tries to re-assign the `console` binding--a healthy side-effect!

**Comment by nemanjan00** [comment]
Thank you! 

I actually do override console.log quite a bit, so, I guess it is best to just put this code inside ignore block... 

Thank you a lor fot explanation! :)

**Comment by jugglinmike** [comment]
Sure thing!
