### ISSUE TITLE
Unexpected escape character '<' 

### ISSUE THREAD

**Issue by NN---** [jshint/jshint#3238]
JSHint: 2.9.5.

Complains about this regex:

```js
rquickExpr = /^(?:#((?:[\w-]|\\(?:\!|\"|\#|\$|\%|\&|\'|\(|\)|\*|\+|\,|\-|\.|\/|\:|\;|\<|\=|\>|\?|\@|\\|\[|\]|\^|\`|\{|\||\}|\~)|\\[a-f0-9]{1,6})+)|(\w+)|(?:.((?:[\w-]|\\(?:\!|\"|\#|\$|\%|\&|\'|\(|\)|\*|\+|\,|\-|\.|\/|\:|\;|\<|\=|\>|\?|\@|\\|\[|\]|\^|\`|\{|\||\}|\~)|\\[a-f0-9]{1,6})+)))$/,
```

**Comment by jugglinmike** [comment]
Hi there,

That warning seems appropriate. There doesn't seem to be any need to escape the
`<` character. Does removing the leading forward slash `\` have any effect on
the behavior of the regular expression?

**Comment by NN---** [comment]
No need I think, but I don’t see any error in JS.

**Comment by jugglinmike** [comment]
Ah, I see. JSHint makes a distinction between "errors" (which it reports for syntactically invalid code) and "warnings" (which it reports for objectively "suspicious" patterns). (This isn't completely consistent, but [we're working on it](https://github.com/jshint/jshint/pull/3051).)

So in this case, the warning is appropriate. Like any warning, because it is subjective, you may selectively disable it via configuration by referencing it via its code: `-W049: true`
