### ISSUE TITLE
jshint gives an "Expected '(' and instead saw '{'." error when it encounters an async anonymous function

### ISSUE THREAD

**Issue by simoncpu** [jshint/jshint#3244]
**Code**
```
$ cat curlyerror.js
(async () => {
})();
```

**Result**
```
$ cat package.json
{
  // (removed)
  "jshintConfig": {
    "esversion": 6,
    "node": true
  }
}
$ jshint --version
jshint v2.9.5
$ jshint curlyerror.js
curlyerror.js: line 1, col 14, Expected '(' and instead saw '{'.
curlyerror.js: line 2, col 1, Expected an identifier and instead saw '}'.
curlyerror.js: line 2, col 5, Expected ')' to match '(' from line 1 and instead saw ';'.
curlyerror.js: line 2, col 5, Expected an assignment or function call and instead saw an expression.
curlyerror.js: line 2, col 6, Missing semicolon.

5 errors
```

**Comment by simoncpu** [comment]
Turns out that jshint doesn't support await/async yet. I switched to eslint for the mean time and enabled the `"ecmaVersion": 8` option.

**Comment by jugglinmike** [comment]
[A quick search of this project's open issues for the word "async"](https://github.com/jshint/jshint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+async) turns up the existing feature request for async functions: gh-2604. I'm going to close this request to keep the discussion centralized to the one issue.

Thanks for your interest in JSHint!

**Comment by michael004** [comment]
Why javascript in Vscode and Cpanel Web Hosting "different"?

I Tested my code in Vscode and there's no error but in Cpanel because i want to make a website there's an error like this

![cpanel error](https://github.com/user-attachments/assets/1ccaf7fb-11c3-4528-92b5-7333400c884e)
![error details](https://github.com/user-attachments/assets/0a442ea8-eddb-4360-890a-79854582a407)
![vscode](https://github.com/user-attachments/assets/e79886f0-eeb8-4ac4-bc8b-7603ff80bf8e)

i hope you can see the image i gave

**Comment by D-Daveloper** [comment]
i have the same issue too did you fix it?
