### ISSUE TITLE
JSX

### ISSUE THREAD

**Issue by Belabz** [jshint/jshint#3268]
Hi,
I need your help and advice how can i get ride of the jshint warning regarding JSX code or react globally?

Best regards.

**Comment by jugglinmike** [comment]
JSHint does not support JSX because it is a non-standard extension to the JavaScript programming language. This means there is no way to ignore JSX syntax globally, but you may use the `ignoreDelimiters` options to selectively ignore parts of your source code. [This unit test demonstrates how that can be done.](https://github.com/jshint/jshint/blob/6aee2fd434cbd1fc9c449336162cec7b229ea99e/tests/unit/fixtures/ignoreDelimiters.js)

**Comment by Belabz** [comment]
Thank you :)

====================
Belabz Tech
Abdelaziz *BELKOURA*
Belabz.tech@gmail.com

On 15 April 2018 at 22:09:05, jugglinmike (notifications@github.com) wrote:

JSHint does not support JSX because it is a non-standard extension to the
JavaScript programming language. This means there is no way to ignore JSX
syntax globally, but you may use the ignoreDelimiters options to
selectively ignore parts of your source code. This unit test demonstrates
how that can be done.
<https://github.com/jshint/jshint/blob/6aee2fd434cbd1fc9c449336162cec7b229ea99e/tests/unit/fixtures/ignoreDelimiters.js>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jshint/jshint/issues/3268#issuecomment-381434244>, or mute
the thread
