### ISSUE TITLE
Error building project: $scope.model.fin = false Missing semicolon

### ISSUE THREAD

**Issue by yvesguerinmtl** [jshint/jshint#3270]
Dear,

I build our project on 2018-04-12 and I got this error:

`Running "jshint:all" (jshint) task
app/areas/messages/messages.js AND app/areas/messages/thread.js
 $scope.model.fin = false Missing semicolon.
$scope.model.fin = true Missing semicolon.`

I rebuild the same project today (2018-04-13) and no error ?!

I double checked my nexus repository and I got an update for the jshint/-/jshint-2.5.11.tgz:
 `Last downloaded  Thu Apr 12 2018 12:34:51 GMT-0400 (EDT)`

I am using : grunt-contrib-jshint/-/grunt-contrib-jshint-0.10.0.tgz
`Last downloaded Fri Apr 13 2018 11:59:07 GMT-0400 (EDT)`

So I am wondering why those versions are updated ?!

Regards.

**Comment by yvesguerinmtl** [comment]
Dear,


Thank you in advance for your help.


The problem is with JSHint itself or with grunt-contrib-jshint because:


the 11th of april I was able to compile my project but on the 12th April I got the following error:


Running "jshint:all" (jshint) task app/areas/messages/messages.js AND app/areas/messages/thread.js $scope.model.fin = false Missing semicolon. $scope.model.fin = true Missing semicolon.


So I tried the 13th April and everything went right !?


I use Nexus as npm proxy to npm repository but I double checked the date on my Nexus repository and the package jshint/-/jshint-2.5.11.tgz was updated on Thu Apr 12 2018 12:34:51 GMT-0400 (EDT).  So I checked on github and I saw the "Latest commit e0b4e91 <https://github.com/jshint/jshint/commit/e0b4e91ba601c316ffd64c724cf972c51e180f65> on Mar 11".  I used the version 2.5.11 of JShint and I am wondering why my Nexus repository was updated because the version I used should be stable/freeze (no more update) ?


Regards,


Yves


Yves Guerin

Analyste-programmeur senior

yves.guerin@groupe-gsc.qc.ca<mailto:yves.guerin@groupe-gsc.qc.ca>

[1505220845841_groupe-gsc.jpg]

CERTIFIÉ ISO 9001



T. 514.354.4222 x 229

F. 514.354.3312



10 905, BOULEVARD LOUIS-H.-LAFONTAINE, BUREAU 200

MONTRÉAL (QC)  H1J 2E8

www.groupe-gsc.qc.ca<http://www.groupe-gsc.qc.ca/>

www.hygeeplus.com<http://www.hygeeplus.com>



[1505221020060_image002.jpg]

Ce message et les renseignements qu'il contient sont exclusifs et confidentiels et sont assujettis à la politique de Groupe GSC que vous pouvez consulter au http://groupe-gsc.qc.ca/confidentialite-courriel/
This message and the information contained herein is proprietary and confidential and subject to the Groupe GSC policy statement, you may review at http://groupe-gsc.qc.ca/confidentialite-courriel/




________________________________

**Comment by jugglinmike** [comment]
It sounds as though your system has updated your version of JSHint without your
instruction to do so. That's unfortunate, but there isn't much the maintainers
of JSHint can do to fix that issue here. Your best bet for a short-term fix is
to debug your system and the way it specifies and retrieves dependencies.

However, I may still be able to offer some assistance.

JSHint tries to maintain backwards compatibility between major releases. If
upgrading from version 2.5.11 to version 2.9.5 has introduced new failures, you
may have uncovered a regression in the library.

However, from the source code you have shared, it looks like JSHint is
correctly identifying a case where a semicolon was omitted. If that is true,
then you may be able to silence the warning by disabling the code "W033" (see
the project documentation for instructions on how to do this). I can't say
this definitively because JSHint has a "warning" and an "error" for "missing
semicolons". It is not possible to disable errors, but I can't determine which
kind of message JSHint is reporting from the output you have shared. The command
line interface supports a `--verbose` flag which will cause it to output the
specific message identifier--that will clear things up.

Alternatively, you could modify your source code to insert the missing
semicolon.

**Comment by yvesguerinmtl** [comment]
Dear,

Thank you for your answer.  To be short and sweet, I modified my build script to add the semicolon and to get the project up and running.
I will look into the Nexus repository, but I think (ok I hope)  that Nexus only update files if they have different size and/or different signature from the original repository (JShint).  Has you already know,  the way they (developers) did things are always different from your normal understanding and the way you will code it if you have to do it.

Thank you so much for your help.

**Comment by yvesguerinmtl** [comment]
Dear,

I close this issue :)
