### ISSUE TITLE
jshint

### ISSUE THREAD

**Issue by maria2067** [jshint/jshint#3294]
jshint
https://github.com/jshint/jshint/issues

**Comment by jugglinmike** [comment]
Hi there! This issue doesn't have any actionable information, so I suspect you
may have filed it mistakenly. That's why I'm going to close this issue.

If you're having trouble using JSHint, check out [the contribution
guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md) to
see the kind of information we'll need to help. If you're ust getting started
with GitHub.com, you might try https://lab.github.com/ to learn more about
interacting with projects on the website.
