### ISSUE TITLE
esversion set to 6 yet jshint says "missing semicolon" 

### ISSUE THREAD

**Issue by JoeCodeswell** [jshint/jshint#3302]
Hi folks,
I thought es6 doesn't need semicolons. 
One of my favorite features!  :)
Why is jshint saying "missing semicolon" when i have set option esversion:6 ?
/*jshint esversion:6, unused:false, eqnull:true  */
Thanks.
Love and peace,
Joe

**Comment by jugglinmike** [comment]
The behavior you're looking for is called "automatic semicolon insertion," and it's been a part of JavaScript since well before ES6. Since it's orthogonal to the language's version, JSHint offers a separate configuration option to enable it: `asi`. From [the project documentation](http://jshint.com/docs/options/):

> `asi` This option suppresses warnings about missing semicolons. [...]

Hope that helps!
