### ISSUE TITLE
Missing If Condition does not raise error

### ISSUE THREAD

**Issue by MattRudy-Kandrea** [jshint/jshint#3313]
Missing third condition with syntax below does not raise error. UI does not flag issue although the empty condition within brackets is invalid.

**if(variableA && variableB && () ) {
    //Do something
}**

Version 2.9.4

**Comment by jugglinmike** [comment]
Thanks for the report. The `if` statement is a bit of a red herring. The real problem is with the grouping operator itself. This has previously been reported in gh-2863. We also have a patch for it (gh-2865), but believe it or not, fixing this would be a backwards-breaking change, so we have to wait for the next major release.

I'm going to close this issue since we already have an issue to document the problem.
