### ISSUE TITLE
`"` and `\"` are considered as different keys

### ISSUE THREAD

**Issue by iogorodov** [jshint/jshint#3315]
JsHint version: 2.9.6

Code:
```
var x = {
  '"': 10,
  '\"': 20,
};
```

Configuration: default

Result: no warnings

Expected result: W075: Duplicate key

**Comment by jugglinmike** [comment]
Thanks for the report! We just released version 2.9.6 yesterday, so we're on the lookout for regressions. This does not appear to be one: I can reproduce it in version 2.9.0 (and likely earlier than that). We definitely want to fix this, but we won't prioritize it like we would a breaking change.

**Comment by jugglinmike** [comment]
Also, since this seems like it should have a relatively well-contained solution, I've labeled it with "Good first bug." Any chance you'd like to help out, @iogorodov?

**Comment by iogorodov** [comment]
Actually I don't find well-contained solution. Simple and dirty solution is fixing escaped double quotes in `propertyName` function:
```diff
     if (!id) {
       if (state.tokens.next.id === "(string)") {
-        id = state.tokens.next.value;
+        id = state.tokens.next.value.replace(/\\"/g, "\"");
         if (!preserve) {
           advance();
         }
```

I've made commit with such fix (tests included) within my fork, but I don't think that its proper solution. As for my opinion core issue is that lexer returns different tokens for double quote with and without escape, but playing with lexer definitely breaks output and possible some tests

**Comment by manisai216** [comment]
Hi, 
Is this issue still open? I would like to work on this. I am a first time contributor. Any help is appreciated.

**Comment by jugglinmike** [comment]
Yes, this issue is indeed still open. The problem appears to be in how JSHint
interprets escape sequences in string literals. That's the job of the lexer, so
we'll probably be working in the file named `src/lex.js`.

Also, it looks like this is related to the "double quote" character (`"`)
specifically; it's not a problem with a single quote. Take this program for
example:

```js
void {
  '"': 0,
  '\"': 0,
  "'": 0,
  "\'": 0
};
```

Given that, JSHint reports the following error:

```
./2021-07-03-strings-2.js: line 5, col 7, Duplicate key '''.

1 error
```

Even though there are two different pairs of duplicate keys, we only see an
error about the single quote.

So, we can start by finding the code for string escape sequences in
`src/lex.js` and finding why it treats the single quote character and the
double quote character differently.

Does that help?

**Comment by manisai216** [comment]
@jugglinmike Yes, I got the issue and the place where I have to look. I will soon a PR for this. Thanks for the help!!

**Comment by jugglinmike** [comment]
Thanks, @maayami! We can talk through the technical details of your patch in the discussion thread of the pull request itself :)
