### ISSUE TITLE
'object short notation is available in ES6' what does it mean

### ISSUE THREAD

**Issue by Yang09701194** [jshint/jshint#3324]
Hi, I'm confused about the hint **`object short notation is available in ES6`** with code below, what does it mean?

![image](https://user-images.githubusercontent.com/23180780/44402122-5b8bfd80-a583-11e8-8e21-5ede03cca4a8.png)

```
function Person(first, last, age, gender, interests){
    this.name ={ first, last  }; 
}
```

**Comment by jugglinmike** [comment]
Hi there! The warning is referring to the use of an IdentifierName in an object
literal. For example:

```js
var property = 23;
var object = { property };
```

This syntax was introduced in ES6/ES2015, so JSHint will issue a warning if it
encounters it in a file that has not been configured for that version of the
language.

Since the code is running for you, I assume that the use of ES2015 syntax is
appropriate in your project. If that's right, then you can address this by
letting JSHint know that you'd like to use the new language features. You can
do that in either one of two ways:

1. Via an inline directive at the top of your source code file: `/* jshint esversion: 2015 */`
2. Via a JSHint configuration file (typically named `.jshintrc`:

   ```json
   { "esversion": 2015 }
   ```

Does that help?

I'm also interested in making this more clear. This particular language feature
does not have an official name, We chose "object short notation," but [the
Kangax Compatibiity Tables](https://kangax.github.io/compat-table/es6/) refers
to it as "shorthand properties." What term do you use to describe this syntax?

**Comment by Yang09701194** [comment]
Thank you, after adding `/* jshint esversion: 2015 */`, the hint disappear, and after reading your explanation I understand what it means, it does help!

I would suggest if it's possible, could consider to make a doc to explain more or give example to hints that are little not easily understand, such as [MS do in C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246).

I'm new to javascript so I could not give my opinion now, and for me this issue is solved, so I don't mind to see it be closed, thank you again!
