### ISSUE TITLE
please i use const in my code and its is showing me this:'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)jshint(W104)

### ISSUE THREAD

**Issue by louis935** [jshint/jshint#3373]

**Comment by NehemiahAT** [comment]
I believe this is warning you about browser support.  ES6 is not supported among all browsers.

**Comment by jugglinmike** [comment]
This is expected behavior. By default, JSHint assumes the input is intended for an ECMAScript 5 environment. If you would like to use an ES6 feature like `const`, then you'll need to configure JSHint accordingly. The warning you're seeing gives instructions on how to do that, and you can also read more about configuring JSHint on the website, https://jshint.com
