### ISSUE TITLE
JSHint Complains 'Missing Semicolon' on W3Schools Code

### ISSUE THREAD

**Issue by NehemiahAT** [jshint/jshint#3375]
I am trying to make a digital version of the German Enigma machine.  I am using the JavaScript onclick event using edited W3Schools code: `document.getElementById("qKey").onclick = function() {PressedQKey()};`.  However, JSHint complains that a semicolon is missing.  

I noticed that if I changed the code to `document.getElementById("qKey").onclick = function() {PressedQKey();};`, the complaint would dissappear.  

W3Schools page refrenced:  https://www.w3schools.com/jsref/event_onclick.asp. 

JavaScript file I am writing: https://github.com/NehemiahAT/Enigma-Commercial-Version-/blob/master/enigmawires.js.

**Comment by NehemiahAT** [comment]
JavaScript file I am writing:  https://github.com/NehemiahAT/Enigma-Commercial-Version-/blob/master/enigmawires.js.

**Comment by jugglinmike** [comment]
This is expected behavior. By default, JSHint warns about code which relies on Automatic Semicolon Insertion. You may either update the code to include the omitted semicolons, or you may enable the `asi` linting option.

You can read more about all of the available linting options in JSHint's documentation:

https://jshint.com/docs/options

**Comment by NehemiahAT** [comment]
@jugglinmike Thank you for the information.
