### ISSUE TITLE
So confused with Warning  error im getting

### ISSUE THREAD

**Issue by RobFosterNYC** [jshint/jshint#3383]
I recently installed JShint extension in VS Code.
and after I did, everything in my code went nuts.
Before I installed the JSHint extension, I was perfectly writing code including ES6 code,
without any problems.
But as soon as I installed the JSHint extension, this is what I get.
.
![Screenshot_36](https://user-images.githubusercontent.com/18384135/55397734-dd2e0b80-5514-11e9-8a3c-852cd3d7f8de.png)

Also, before installing the extension, I never needed to put semi-colons,
and now every line is requiring it.
I thought, ES6 and even newer ECMAScript specifically said, one no longer is required to place Semi-Colons as the end of line. among MANY new features.

Its also telling me that ( let ) word is wrong and that I have to install or configure ES6 now on my file.
It was working just fine before I installed JSHint.
Is JSHint that outdated and yet to release a new version for ES6 and above or is something else broken ?

Also how do I configure this to recognize ES6 or above.?
and where can I find the file to do this please.?
Because im so confused right now.
thanks.

**Comment by jugglinmike** [comment]
@RobFosterNYC it looks like you've installed JSHint through an extension for your editor (rather than from npm directly). We don't maintain any editor extensions here, so I can only offer some guesses.

JSHint seems to be running with the default configuration. In that mode, it parses input code as ES5. If you'd like to use ES6, you can follow the advice of the warning message and configure JSHint with the "esversion" option set to "6". I'm not sure how this is done in the extension you are using, but I'm sure that project will have instructions.

**Comment by RobFosterNYC** [comment]
@jugglinmike  The extension I was using was this one:
https://github.com/Microsoft/vscode-jshint     But Through the extension within VS Code.  
someone told me that it was your JSHint and that microsoft supported it,
and the reason why it was under microsoft.  -- I guess that person misinformed me, or just completely lied to me to sound important.  .... Anyways.   im still leanring github, so its a bit difficult for me to nav around.
Besides that, I have a concern......  the standard these days is ES6 or above.  So why JSHint defaults to ES5 when it should be defaulted to what everyone is mainly using which is ES6. ?
only a few devs are using ES5 these days (for those legacy projects or special developments),  but the standard is ES6 in 2019, so I believe that this group should
start implementing the default to ES6 or above "as a default" when ppl install your product.
but thats just my opinion, which really doesnt matter much.
.
Anyways, I appreciate the response and all the help which is greatly appreciated always  :D 
I got frustrated the other day and uninstalled JSHint and installed ESLint (AirBnB) Edition.
for the time being. 
maybe ill give JSHint sometimes in the future. who knows :)

**Comment by jugglinmike** [comment]
Today's standard is ES2018 which is distinct from ES6. We haven't switched the default from ES5 because there's no objective measure for which edition is most common. We haven't received any requests to change (that I can recall, anyway), so it seems folks are fine configuring based on the version they are targeting. If you'd like to gauge interest in changing the default among other JSHint users, that would make for a good new issue. Please feel free to open one.

It sounds like the problem you were having was specific to how the vscode-jshint project accepts configuration, so I'm going to close this issue.
