### ISSUE TITLE
don't get error when "a variable is not a function"

### ISSUE THREAD

**Issue by yalondpsi** [jshint/jshint#3399]
Hi
The code:
`
var a;
a();
`
Does not raise an error "a is not a function"

**Comment by jugglinmike** [comment]
JSHint operates through static analysis. That means it does not execute the
input program. Instead, it issues warnings based on what it is able to infer
from inspecting the source code. In simple cases like your example, tracking
the type of a variable may seem like a tractable problem. However, because
JavaScript does not have a type system, this problem is not possible to solve
generally.

**Comment by yalondpsi** [comment]
Ok Thanks!
