### ISSUE TITLE
showing Error (E043) on "Too many errors", when those "Errors" are only warnings

### ISSUE THREAD

**Issue by paponius** [jshint/jshint#3444]
There should be a separate counter for warnings and for errors.
And separate giving up actions and messages: "Too many Errors" and "Too many Warnings"

I came accross two cases where this is specially important.

I use `debug['something']` throughout the code. There is a reason for that and it's valid. I hid the warning. Not by jshint options. Now all I see is one error saying there is too many errors.
It was quite a time-waster issue finding out what was going on.

Yes, I tried // jshint -W069 instead and the error was not there anymore, probably warnings hidden by jshint options are not counted.
But it does not mean that the logic of a common counter is ok.
Many times jshint is not used directly and warnings could be hidden upstream.

A lot of scripts use jshint to check user-added scripts for errors before executing them in its environment.
They should be set to ignore all warnings or set the maxerr too high. Tamper Monkey seems to be doing that. But it is not something to be expected naturally.

There is a closed issue: https://github.com/jshint/jshint/issues/180,
but the proposed solutions were to remove the feature, or make it opt-in.

What I mean here is that the feature itself is not an issue, but joining counts of warnings and errors and reacting with one common action is.

**Comment by jugglinmike** [comment]
Thanks for the report!

A bit of background:

Errors describe problems in parsing, so they often appear in large numbers following a single syntax error. That's because JSHint attempts to recover from invalid syntax as a convenience to the user. Recovery involves some guesswork, so there's no foolproof way to do it. If JSHint guesses incorrectly, then it will end up reporting a large number of irrelevant errors.

Warnings, on the other hand, are reported in response to discrete patterns in the code. They're far less likely to exhibit the same kind of "avalanche" that sometimes occurs for errors.

Also note that the threshold for "giving up" is configurable via the `maxerr` option. Just like the error message, this option currently conflates the term "error" and "warning."

It seems to me like this behavior is only really relevant for errors. In that case, it may be appropriate to limit it to errors only. What do you think, @paponius?

**Comment by paponius** [comment]
I think that's exactly what I had in mind.

From what I gathered and how I understand it, `maxerr` is there mainly to stop linting and report an error early, exactly because one error, a missing '}' might cause many lint errors, which might slow down whatever is above the jshint, specially in case of a long script. For example an editor in which I am just editing the line where '}' will be.

That's where maxerr comes handy and when used for on-the-fly lint while editing, I'll even consider lowering it to 5. If I see more than 3 errors, it's always actually just one error followed by the avalanche.

But I should not get an error because of warnings.
It's not an error to do something not-by-book, even if it's done 50 times.

I can see three solutions
1. separate `maxerr` and (additional) `maxwarn`
2. one `maxerr` setting, but two counters, so 49 errors plus 49 warnings will still not trigger 'too many errors'.

Plus for both 1 and 2,
- 'too many warnings' would not show as an error, but as a warning.
- it would not stop linting the rest of the script for errors.
3. no counter for too many warnings at all. Not stopping on too many warnings or showing a message "too many ..."

I would go with 3, as you proposed, because it's easiest and from how I see it, there is little reason to stop on too many warnings.

I discussed this issue also on SublimeLinter project, which is an interface between Sublime Text editor and jshint (or other lint). That's the one I mentioned in first post, offering filter above jshint warnings, which will hide warnings user does not want to see but possibly resulting in Sublime reporting just one error: 'too many errors', without seeing those hidden warnings, what's quite confusing.
There is not much that can be done there to avoid this except for removing (maxerr=9999) or at least changing the text of the error.
But if there were both options 'maxerr' and 'maxwarn', or no max for warn at all, that would solve the issue there too.

**Comment by jugglinmike** [comment]
The first approach sounds good to me: limit `maxerr` to errors only. If you (or anyone else) would like to try making this change, I'll be happy to provide guidance.

**Comment by alexanderbrown21** [comment]
how's it going with this issue :) ?

**Comment by dhruv479** [comment]
@jugglinmike I will make the required change, provide me with some guidance

**Comment by jugglinmike** [comment]
Sure, @dhruv479. Here are the changes that come to mind:

- `src/jshint.js` - update the condition that causes the `E043` error to be emitted. Keep in mind that `JSHINT.errors` is a misleading name because its elements describe both warnings and errors. The condition should only count the elements in the array that describe errors
- `tests/` - update any tests that this causes to fail, and add a new test if necessary
- `src/options.js` - update the documentation of the `maxerr` option

...though you might find still more things that need to be changed!

**Comment by dhruv479** [comment]
Hey @jugglinmike, I will do the required and share the PR.

**Comment by Ashesh3** [comment]
Hello @jugglinmike , I have made a PR to address this issue. Happy to accommodate any further changes. Hope it helps!
