### ISSUE TITLE
W067 Bad invocation on immediate invocation tagged string template

### ISSUE THREAD

**Issue by Nikita-Boyarskikh** [jshint/jshint#3459]
Hello!

I'm using `jest` `each` feature and white parametrized test like described in [official Jest documentation](https://jestjs.io/docs/en/api#2--testeachtablename-fn-timeout-)
```js
1 test.each`
2 a    | b    | expected
3 ${1} | ${1} | ${2}
4 ${1} | ${2} | ${3}
5 ${2} | ${1} | ${3}
6 `('returns $expected when $a is added $b', ({a, b, expected}) => {
7     expect(a + b).toBe(expected);
8 });
```
And JSHint get W067 at 6th line and 2nd simbol.

My JSHint version: `2.10.2`
My JSHint config:
```json
{
  "esversion"    : 9,
  "asi"          : false,
  "bitwise"      : true,
  "boss"         : true,
  "browser"      : true,
  "couch"        : true,
  "curly"        : true,
  "debug"        : false,
  "devel"        : true,
  "eqeqeq"       : true,
  "eqnull"       : false,
  "evil"         : true,
  "expr"         : true,
  "forin"        : false,
  "globalstrict" : false,
  "immed"        : true,
  "jquery"       : true,
  "latedef"      : true,
  "laxbreak"     : true,
  "loopfunc"     : true,
  "mootools"     : false,
  "newcap"       : true,
  "noarg"        : true,
  "node"         : false,
  "noempty"      : false,
  "nonew"        : true,
  "nomen"        : false,
  "onevar"       : false,
  "passfail"     : false,
  "plusplus"     : false,
  "prototypejs"  : false,
  "regexdash"    : true,
  "regexp"       : true,
  "rhino"        : false,
  "undef"        : true,
  "shadow"       : true,
  "strict"       : false,
  "sub"          : true,
  "supernew"     : true,
  "trailing"     : true,
  "white"        : false,
  "wsh"          : false,
  "unused"       : true,

  "indent"       : 4,
  "maxlen"       : 120,

  "predef"       : [
    "define",
    "_",
    "requirejs",
    "describe",
    "jest",
    "it",
    "expect",
    "beforeAll",
    "beforeEach",
    "afterAll",
    "afterEach"
  ]
}
```

**Comment by jugglinmike** [comment]
Thanks for taking the time to file an issue! The message "Bad invocation" is very vague, but it is describing a stylistic consideration. The code is still technically valid, and that's why the message is reported as a warning and not an error. You can disable that warning (or any other warning) via special code comment (a JSHint "directive") or via a configuration file.

The warning you're reporting is identified as W067. You can disable that with a directive by including the following comment in the file:

    // jshint -W067

Or you can disable it across many files by including the following property in your JSHint configuration file (typically named `.jshintrc`):

    {
      "-W067": true
    }

For what it's worth, I can share a guess about the spirit of the curt message, "Bad invocation." The invocation is a little unorthodox (it's not every day you see a tagged template returning a function value). That makes it more likely that it's a programming mistake--one that wouldn't otherwise be caught until the code was running. Even when it's intentional (like in your case), other developers may not recognize the pattern or repeat it in their own code.

You shouldn't have to come all this way to get that perspective, though, so I've filed [a pull request to improve the warning message](https://github.com/jshint/jshint/pull/3462). Hopefully that will make the intent more clear and also help folks recognize that it's a recommendation. If you have thoughts about how it could be improved, please leave a comment there!

**Comment by Nikita-Boyarskikh** [comment]
OK, I agree with you.

Thank you for the detailed explanation :)

I believe in the near future everyone will get used to tagged template strings and this syntax will not be able to mislead anyone, but for now I will mute this warningю
