### ISSUE TITLE
node:true yet Promise not defined

### ISSUE THREAD

**Issue by ryanburnette** [jshint/jshint#3477]
my .jshintrc
```json
{
  "node": true
}
```

my index.js
```js
'use strict';

module.exports = function () {
  return Promise.all([]);
};
```

my result
```bash
$ jshint index.js 
index.js: line 4, col 10, 'Promise' is not defined.

1 error
```

my version
```bash
$ jshint --version
jshint v2.11.1
```

I am not expecting to have to add Promise as a global. Did I miss something in a changelog somewhere?

**Comment by jugglinmike** [comment]
Thanks for filing a report! In general, JSHint's options are independent; `node` describes whether the environment is Node.js, and `esversion` controls the version of ECMAScript. For your use case, I recommend a configuration like

```json
{
  "node": true,
  "esversion": 6
}
```

Though depending on the version of Node.js you are using, you can likely use a larger number for `esversion` (since that describes a more recent version of the language).

Your reference to this project's change log suggests that your expectation was met by a prior release of JSHint. Is that right? If so, could you share the version where this worked as you expected?

**Comment by ryanburnette** [comment]
I tested and found this behavior consistent on the last dozen or so releases. I am now setting `esversion` in all my project `.jshintrc` files. Maybe it was an issue with my global `.jshintrc`.

**Comment by jugglinmike** [comment]
Ah, glad it's working!
