### ISSUE TITLE
W117

### ISSUE THREAD

**Issue by vkwd** [jshint/jshint#3521]

**Comment by fbarda** [comment]
Please be more clear at what is your issue.

---
You can turn off a specific warning with `//jshint -W117` and turn it back on with `//jshint +W117`.
Refer to [docs](https://jshint.com/docs/) for more info.

(Documentation of Warning 117 according to [haiyang.me](haiyang.me/read.php?key=500))
![Documentation of Warning 117](https://user-images.githubusercontent.com/30421526/103035195-e1ffe200-4577-11eb-9801-15c9f5591798.png)

The warnings are there to help you write cleaner and better codes! Try to fix the problem rather than avoiding the warnings and errors!

**Comment by jugglinmike** [comment]
There isn't enough information here for anyone to help you. [The project's contribution guidelines have some suggestions for filing an actionable support request](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md); we can re-open this issue once there's more information.
