### ISSUE TITLE
jshint does not work in CLI when passing a directory

### ISSUE THREAD

**Issue by juli1** [jshint/jshint#3526]
When invoking `jshint` with a directory as an argument as mentioned in the [doc](https://jshint.com/docs/cli/), it does not work.

For example, if I have a directory `apollo` with multiple javascript files, it works well if I invoke `jshint` on one file passed as argument. If I pass the whole directory, nothing is returned.

```
jshint apollo/index.jsx 
apollo/index.jsx: line 1, col 1, 'import' is only available in ES6 (use 'esversion: 6').
apollo/index.jsx: line 2, col 1, 'import' is only available in ES6 (use 'esversion: 6').
```

```
jshint apollo
<nothing>
```

For information
```
jshint --version                                                                                                                  
jshint v2.12.0
```

**Comment by jugglinmike** [comment]
Thanks for the report! This sounds like expected behavior to me. By default, the CLI only considers files with a `.js` extensions. One way to override this is to specify the path to a specific file (as in your first example). Another way is through the `--extra-ext` command-line argument. Here's the relevant output from invoking the CLI with the the `--help` argument:

>     -e, --extra-ext STRING Comma-separated list of file extensions to use 
>                            (default is .js)

So if you'd like to see the same warnings in your second example, you'd execute this command instead:

    jshint --extra-ent jsx apollo

Keep in mind, though: JSHint is a JavaScript linter, so it won't recognize the non-standard syntax that's typically used in `.jsx` files.

**Comment by juli1** [comment]
Thanks for your comment, you are correct, thanks for taking the time to answer my question.
