### ISSUE TITLE
No option to disable E054 to not warn when hacking to emulate subclasses.

### ISSUE THREAD

**Issue by 133794m3r** [jshint/jshint#3527]
JSHint won't let you disable the warning for E054 for a "sub" class using the new ECMA2015 class keyword.
```js
class Outer{
	constructor(){
			
	}
	Inner = class {
		 constructor(a_value){
			this.a = a_value;
		}
	}
}
```

JSHint has no option to disable this warning that I can see. So it then just ends up dying. I already know that JavaScript uses prototypal inheritence and thus the "class" itself isn't a private subclass but I prefer to have the object hold that inner one and any variants that it has to do on it instead of declaring it outside of the class. I'm mainly using it for a Node "class" and don't want to have to have a LinkedListNode, GraphNode, etc in each file.

I'd like the option to just disable it as that'd be much simpler than actually parsing the code to figure out this hack of a choice.

**Comment by jugglinmike** [comment]
Thanks for taking the time to write a report!

The use of a "sub-class" is a bit of a red herring. What you're actually running up against is JSHint's lack of support for class fields. That's a new language feature, so we're interested in adding support. I'm going to close this issue because we already have an issue to track that feature: gh-3139.

By the way: message codes that begin with the letter "E" are errors, and those are distinct from warnings. JSHint uses errors to communicate objective problems with syntax. That's why there's no way to disable them. Warnings, on the other hand, are more subjective because they describe dangerous patterns that can be dangerous. Because of this, warnings can be disabled on a case-by-case basis. The project documentation explains the various ways you can achieve that.

**Comment by 133794m3r** [comment]
It had been many many years since I last used jshint. I never thought that it was a literal error in the parser not supporting the feature and causing it to die. I'll just watch that issue and wait till I see it being resolved before I re-use jshint again.
