### ISSUE TITLE
double question mark marked as an error whereas the code can perfectly be executed (node.js)

### ISSUE THREAD

**Issue by ElMaxonDSCRD** [jshint/jshint#3539]
jshint version: **v2.12.0**

```js
const hey = 0 ?? 2;
```
⬆code

```json
"jshint.lintHTML": true,
"jshint.options": {
    "esversion": 10
},
```
⬆config

Expected: no error at all
Actual Behavior: error
`Expected an identifier and instead saw '?'. (E030)`
`Expected ':' and instead saw '2'. (E021)`
`Expected an identifier and instead saw ')'. (E030)`
`Expected an operator and instead saw '*'. (E033)`
`Expected ')' to match '(' from line 41 and instead saw '1000'. (E020)`

![image](https://user-images.githubusercontent.com/77689281/109059572-ac48b800-76e4-11eb-84a5-7f4d72e093e0.png)
⬆error

**Comment by jugglinmike** [comment]
Thanks for the report! The language feature you're looking for is called "nullish coalescing." Although we don't prioritize work based on the behavior of Node.js, nullish coalescing definitely satisfies [our criteria for new features](https://jshint.com/blog/new-lang-features/). Since this was previously requested in gh-3443, I'm going to close this issue to keep things tidy.

You'll be happy to hear that the feature has been implemented and will be included in the next minor release of JSHint. You can watch gh-3486 for updates on that release.
