### ISSUE TITLE
Error W030 shown for no reason

### ISSUE THREAD

**Issue by SiddharthShyniben** [jshint/jshint#3543]
I have the following code:
```js
verbose ? messenger.info(`text ${variable}`) : spinner.text += variable;
```

But I get the `Expected an assignment or function call and instead saw an expression. (W030)` error in this code. ***Why?***

**Comment by SiddharthShyniben** [comment]
I'm using the vscode extension BTW

**Comment by jugglinmike** [comment]
JSHint is reporting warning W030 because a conditional expression (sometimes called a "ternary") is being used for its side-effect. By default, the only expressions which JSHint tolerates in a statement position are function invocations and assignment expressions.

Here are a few different ways you can address this:

- disable warning W030 for your project, the file which contains that code, or that specific line
- enable [the `expr` linting option](https://jshint.com/docs/options/) for your project, the file which contains that code, or the specific line
- refactor the code to use an `if` statement:

  ```js
  if (verbose) {
    messenger.info(`text ${variable}`);
  } else {
    spinner.text += variable;
  }
  ```

[The project documentation](https://jshint.com/docs/) includes instructions for the various ways you can toggle rules and warnings.

**Comment by SiddharthShyniben** [comment]
Great. I'll try it out
