### ISSUE TITLE
if (comparison operator) statement broken for (in) warning

### ISSUE THREAD

**Issue by bill1812** [jshint/jshint#3553]
```javascript
// e.g. 1: No Warning
var a = { x: 1, y: 2, z: 3 };
var b = [];
var c = 0.1;
var d = 0.5;
var e = 0;

for (let i in a) {
  // console.info('output 1: ', a[i]);
  if (c * 10 === 1) {
    console.info('output 2: ', a[i]);
    e = a[i] * 10 * d;
    b.push(e);
  }
}
console.info('b: ', b);

// e.g. 2: for ( in ) WARNING
var a = { x: 1, y: 2, z: 3 };
var b = [];
var c = 0.1;
var d = 0.5;
var e = 0;

for (let i in a) {
  console.info('output 1: ', a[i]);
  if (c * 10 === 1) {
    console.info('output 2: ', a[i]);
    e = a[i] * 10 * d;
    b.push(e);
  }
}
console.info('b: ', b);
```
PS: I used it @ https://jshint.com/

**Comment by jugglinmike** [comment]
If JSHint is configured to use ECMAScript version 6 or later (e.g. with the configuration `esversion: 6`), then it reports exactly one error for the code you've shared:

> The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.

That message describes the motivation for the warning. Generally, you'll want to satisfy it by verifying the presence of the property on the object itself (rather than on an object in the object's prototype chain.) The "if" statements in the example satisfy JSHint's naive heuristic, but they don't actually guard against the problem that the warning is describing. Here's how you might guard against the problem and satisfy JSHint:

```diff
 for (let i in a) {
+  if (Object.hasOwnProperty.call(a, i)) {
     console.info('output 1: ', a[i]);
     if (c * 10 === 1) {
       console.info('output 2: ', a[i]);
       e = a[i] * 10 * d;
       b.push(e);
     }
+  }
 }
```

Hope that helps!

(JSHint's heuristic for detecting the problem is a little primitive. It's satisfied by *any* "if" statement, regardless of whether it actually verifies the property's presence on the object being traversed. Improving that might be an improvement we could make, but since the current behavior is not a bug, anyone wishing to discuss that should create a new issue.)
