### ISSUE TITLE
Is it possible to check uninitialized class properties?

### ISSUE THREAD

**Issue by leolumicrosoft** [jshint/jshint#3554]
Let's say there is a function class with property startNumber
function person(){
   this.startNumber=1
}

"Person" has a prototype function as below,

person.prototype.incrementfunc=function(){
   this.StartNumber++
}

Is it possible jshint can warn that StartNumber is an uninitialized property so developer can easily spot the typo that it should be lowercase "startNumber" instead of "StartNumber"

**Comment by jugglinmike** [comment]
JSHint could catch some of these problems for JavaScript code, but it would require a substantial change to its internals, and the resulting behavior would be inconsistent. I'd say that it's out of scope for the project.

The good news is that other projects have been created to provide the kind of assurance you're looking for. They also specify how to annotate your code with type information since JavaScript is generally too dynamic to analyze statically in this way. A couple places to get started are Flow and TypeScript.
