### ISSUE TITLE
nullish coalescing operator (??) giving warning

### ISSUE THREAD

**Issue by sothix** [jshint/jshint#3561]
The following code is throwing a warning: (ES11 version of ES12 nullish assignment):

```
//jshint esversion:11
let x = null;
x ?? (x = 2);
```
`Expected an assignment or function call and instead saw an expression.`

**Comment by jugglinmike** [comment]
JSHint does not support the nullish coalescing operator. That has previously been requested via gh-3443, so I'm going to close this issue as a duplicate. (By the way, when reporting a bug in any open source project, it's best to start by searching a project's issue tracker in order to familiarize yourself with prior conversation on the topic.)
