### ISSUE TITLE
ES Version 6 vs. 9 incompatibility

### ISSUE THREAD

**Issue by Jollus174** [jshint/jshint#3565]
JSHint version used: **jshint@2.13.1**.

On our local machines we use Babel to transpile our JS code, but before it executes we use JS Hint to make sure that it's clean and free of errors.

Our Babel is configured to transpile ES9 and ES6 to ES5, but I've been running into some issues with `esversion`. Normally our version is set to `"esversion": 9`, but then ES6-related errors will occur in the presence of arrow functions.
```
/* jshint esversion: 9 */
const testES6 = (exampleText) => { // Warning: 'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6')
	return exampleText;
};
testES6('some example text); // Expected output 'some example text'

const fruits = ['apples', 'oranges', 'bananas'];
const testES9 = {
	...fruits
}
console.log(testES9[1]); // Expected output 'oranges'
```

If we set it to `"esversion": 6`, then the ES9 spread will fail.
```
/* jshint esversion: 6 */
const testES6 = (exampleText) => {
	return exampleText;
};
testES6('some example text); // Expected output 'some example text'

const fruits = ['apples', 'oranges', 'bananas'];
const testES9 = {
	...fruits // Warning: 'object spread property' is only available in ES9 (use 'esversion: 9')
}
console.log(testES9[1]); // Expected output 'oranges'
```

Was there a way that we could have 'esversion: 9' use ES version 9 as well as support versions below it?

**Comment by jugglinmike** [comment]
Each version of the language subsumes the one that came before it, so setting the `esversion` to `9` ought to enable support for both object spread syntax and arrow function syntax.

When I pasted the first example code into the editor hosted on https://jshint.com, JSHint reported a large number of errors due to an unrelated syntax error. After I fixed that, JSHint accepted both the object spread syntax and the arrow function, as expected for "esversion: 9":

```diff
 /* jshint esversion: 9 */
 const testES6 = (exampleText) => { // Warning: 'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6')
     return exampleText;
 };
-testES6('some example text); // Expected output 'some example text'
+testES6('some example text'); // Expected output 'some example text'
 
 const fruits = ['apples', 'oranges', 'bananas'];
 const testES9 = {
     ...fruits
 }
 console.log(testES9[1]); // Expected output 'oranges'
```

Probably the syntax error was just a mistake when filing the issue, but it does make me wonder if there are more subtle differences between your code base and the sample code.

Could you verify that JSHint doesn't report syntax errors for that code? And if so, could you provide anoter example?

**Comment by Jollus174** [comment]
@jugglinmike Thanks for your feedback! I've done a little more investigation.
When you mentioned that each version should subsume the previous one, that put me on the right path.
You're right, there were some minor syntactic issues with the examples, but it turned out the issue was that globally I was indeed using `jshint@2.13.1`, but the local project was using `"grunt-contrib-jshint": "~1.0.0"`, which was resolving to v1.0.0 in package-lock.json.
Setting it to be "~3.0.0" (the latest version) has now fixed that issue when it's compiling.
