### ISSUE TITLE
Does JSHint support customized rules?

### ISSUE THREAD

**Issue by suaha** [jshint/jshint#3583]
Hi,

I am trying to use JSHint in my project, but due to my application requirement besides the regular rules I need to validate JS in a special way.

Is  there a way I can customize JSHint rules?

Regards

Wen

**Comment by jugglinmike** [comment]
Hi there! JSHint does not support the kind of extension that you're describing. You may be able to acheive what you're after by altering the source code. Future release of JSHint may conflict with your changes, though. If your work would be useful to others, we might be able to accept it into the repository itself. If you think that's feasible, then we typically start with a discussion of the new feature here in the project's issue tracker and move on with implementation after that.

Otherwise, you may want to consider another tool to validate your source code.

Hope this helps!
