### ISSUE TITLE
[security] upgrade shelljs version to 0.8.5

### ISSUE THREAD

**Issue by nodesocket** [jshint/jshint#3599]
There is a known high security impact exploit in the version of shelljs used https://github.com/jshint/jshint/blob/main/package.json#L49.

See the following [huntr.dev](https://huntr.dev/bounties/50996581-c08e-4eed-a90e-c0bac082679c/) for full details and the official [GitHub issue from shelljs](https://github.com/shelljs/shelljs/issues/1058).

Fix should just be pinning to version `0.8.5` and making sure the api did not change and break anything after the upgrade.

**Comment by nfischer** [comment]
:wave: ShellJS maintainer here!

There's some significant API and behavior changes between 0.3.x and 0.8.5, so this particular project will need to exercise some caution when upgrading (but I still recommend that as the path forward). https://github.com/shelljs/shelljs/wiki/Breaking-Changes is a good place to start. This doesn't cover all the way back to 0.3.x, but it should help you get through the last few versions. IIRC there weren't too many major API changes between v0.7 and v0.8 (which is probably why I didn't write a migration guide for that version).

Let me know how I can help.

**Comment by jugglinmike** [comment]
Thanks for the heads-up, Justin and Nate! This project's coupling with shelljs extends beyond the CLI code: [the automated tests perform a lot of mocking in order to validate behavior](https://github.com/jshint/jshint/blob/2a842ac5891916d93356ada81d7cd73918d4f443/tests/cli.js).

I haven't looked in to what it will take to upgrade versions yet, but this may be a good time to consider alternatives. JSHint's support for Rhino was broken years ago, partly because it differs significantly from what's available in Node.js. [Since there's still interest in using JSHint in that context](https://github.com/jshint/jshint/issues/3587), I want to cast a wide net for solutions.

**Comment by nodesocket** [comment]
@jugglinmike I can appreciate upgrading shelljs breaking the automated tests and requiring some work and effort. However, @nfischer was nice enough to offer the [migration guide](https://github.com/shelljs/shelljs/wiki/Breaking-Changes) which should get us most of the way there.

GitHub is flagging `jshint` as having a security vulnerability because of its dependency on shelljs, so I'd argue it's worth the effort to upgrade shelljs to 0.8.5.

![Uploading Screen Shot 2022-01-17 at 6.41.12 PM.png…]()

**Comment by nfischer** [comment]
_Almost_ all of the usage you're changing in #3603 should continue to work in shelljs@0.8.5. If you'd like to keep ShellJS as a dep, I'd be happy to review the few spots which need to change. The main difference is that commands now return a string-like object called `ShellString` with some extra methods, but you can easily convert that to a regular string with `.toString()`.

Of course it's totally up to you if you'd rather drop ShellJS as a dep.

> I haven't looked in to what it will take to upgrade versions yet, but this may be a good time to consider alternatives. JSHint's support for Rhino was broken years ago, partly because it differs significantly from what's available in Node.js. Since there's still interest in using JSHint in that context, I want to cast a wide net for solutions.

I'm not sure what Rhino has to do with ShellJS. Perhaps I'm missing something?

**Comment by jugglinmike** [comment]
We just published JSHint version 2.13.4 to include a fix for this: https://jshint.com/blog/2022-01-24/release-2-13-4/

@nfischer Since shelljs uses Node.js-specific APIs to do its job, code which relies on it can't easily be reused in other environments like Rhino. By defining a custom interface for filesystem operations, JSHint will still be coupled to Node.js, but we'll have a much smaller surface to re-implement to support alternative environments.
