### ISSUE TITLE
Syntax error on numbers with underscores, such as 1_000_000

### ISSUE THREAD

**Issue by coolaj86** [jshint/jshint#3606]
As with other modern languages, JavaScript numbers may contain `_`.

Examples:

```js
let population = 8_501_000_000;
let cents = 1_000_000_00;
```

jshint doesn't seem to be able to parse numbers that use underscores. It fails on the first digit whenever underscores are used:

```txt
[jshint] Unexpected '1'. [E]
```

**Comment by jugglinmike** [comment]
Thanks for taking the time to file an issue! The language feature you are looking for is called "numeric separators", and if you [search this project's issue tracker for that term](https://github.com/jshint/jshint/search?q=numeric+separators&type=issues), you'll find [a corresponding feature request](https://github.com/jshint/jshint/issues/3533). In order to keep things organized, I'm going to close this issue as a duplicate.
