### ISSUE TITLE
Error "Class properties must be methods"

### ISSUE THREAD

**Issue by Hanspe-3019** [jshint/jshint#3607]
With esversion: 8 or higher, I get this error message:

`Class properties must be methods, Expected '(' but instead saw '='`

Sample:

```javascript
class Demo {
    static staticProperty = 'A';
}
console.log(Demo.staticProperty);

```

Script runs as expected, yielding 'A'.

**Comment by jugglinmike** [comment]
Thanks for taking the time to file an issue! The language feature you are looking for is called "numeric separators", and if you [search this project's issue tracker for that term](https://github.com/jshint/jshint/search?q=class+fields&type=issues), you'll find [a corresponding feature request](https://github.com/jshint/jshint/issues/3139). In order to keep things organized, I'm going to close this issue as a duplicate.

**Comment by jacobq** [comment]
> The language feature you are looking for is called "numeric separators"...

This doesn't appear to have anything to do with [numeric separators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#numeric_separators)...but the link to class fields is correct, I guess.
