### ISSUE TITLE
Code with decorators is still throwing E024 errors even with esversion 11

### ISSUE THREAD

**Issue by jking6884** [jshint/jshint#3608]
Shouldn't jshint be able to handle decorators when esversion is set to 11?

![image](https://user-images.githubusercontent.com/4825257/154416917-65a0a1a7-772b-4ccc-a20e-f48a828aac29.png)

**Comment by jugglinmike** [comment]
This is expected behavior. The "function decorators" language feature is not part of ES11--it's still in the proposal process.

(Fortunately, the proposal is mature enough to be implemented here in JSHint, so anyone who would like to submit a patch is more than welcome to do so. Issue gh-2297--which I just now re-opened--tracks the feature request.)

**Comment by jking6884** [comment]
Oh, I see.  I was under the impression that things past a certain stage were supported.  So essentially, decorators are just not implemented in jshint yet then?

**Comment by jugglinmike** [comment]
Yup, that's right
