### ISSUE TITLE
Allow config to override "newcap" for 'use strict'

### ISSUE THREAD

**Issue by axkibe** [jshint/jshint#478]
Setting the option "newcap" to false has no effect, since in line 2482

```

                if (token.value === "use strict") {
                    option.newcap = true;
                    option.undef = true;
                }

´´´

It will be overriden to true again.  Please allow the user to really configure this paramter in config.json and not having it being reset again.

Proposed solution: Just remove these 4 lines since they are set to true by default anyway these lines don't do any good.
```

**Comment by olsonpm** [comment]
Just ran into this issue now.  Pretty annoying I have to say - as I don't want to clutter my js files with a bunch of jshint configuration comments when really I just want a quick manual global run-through.  I come from a c# background and am writing my website with naming conventions more similar to that since it's what I'm used to.  Nobody else is working on my site as it's for personal use.

I guess I'll change the source code - many thanks for pointing out exactly where this option needs to be changed, but honestly this should be considered a bug.
