### ISSUE TITLE
eqeqeq can't be turned off

### ISSUE THREAD

**Issue by mgol** [jshint/jshint#602]
`/*jshint eqeqeq:false */` has no effect. This was reported already in issue #236 which was closed with an incorrect explanation. Problem is seen in Jetbrains IDEs like Webstorm, PHPStorm, PyCharm, IntelliJ IDEA etc.

**Comment by olsonpm** [comment]
I just ran into this myself.  The documentation is vague at best:

> This options prohibits the use of == and != in favor of === and !==

By setting this to false, one would assume the option does  _not_ prohibit the use of == and !=

Would you accept a clarification PR?

**Comment by shanepoints** [comment]
I was battling this for a long time.  It isn't very well documented, but JetBrains uses it's own code analysis that can be configured.  

For OSX the way to configure is:
> &nbsp;&nbsp; _Preferences > Editor > Inspections_

From this screen you can select:
> &nbsp;&nbsp;_Javascript > Probable bugs > Equality operator may cause type coercion_

And then configure the severity of the warning that is issued.  

I would love to be able to disable the feature for just a few lines like you can do with JSHint. That way I will still see the warning in places where it's not intentional. If anyone knows of a way to do this 
I would love to hear it!  Otherwise, maybe the best thing to do is create a combination of this inspection and JSHint.
