### ISSUE TITLE
Option to assume strict mode (for nodejs)

### ISSUE THREAD

**Issue by coolaj86** [jshint/jshint#924]
Now that nodejs is es5 compliant it can be run in strict mode by default without including `(function () { "use strict"; /* code here */ }());`.

Will you add an option `implicitstrict` so that it's not required to have the boilerplate code?

**Comment by englercj** [comment]
Nearly two years since this was opened, is this actually implemented?

**Comment by adriengibrat** [comment]
It's not yet implemented, a [patch](https://github.com/Demeterr/jshint/commit/7b3589f2f33934525f937b207108d9c548100020) was refused because it was mixed with other unrelated stuffs.

Please, it would be nice to implement what @valueof had in mind: [```strict```  multivalue option](https://github.com/jshint/jshint/issues/924#issuecomment-16981384)

**Comment by englercj** [comment]
Any word on when we will have a release with this in it? I've been waiting for it for a while, and it looks like it landed in master.

**Comment by lukeapage** [comment]
@jugglinmike can tell you,  I think one is due soon.

**Comment by mik01aj** [comment]
This gets very annoying with Babel, as it [puts 'use strict'; in front of everything](https://github.com/babel/babel/issues/1844) and explicit `'use strict'` declarations are not necesssary anymore. @lukeapage, could we have a new `2.8.1` release?

**Comment by lukeapage** [comment]
@jugglinmike is working hard to get the next release out. It has alot of
work in it and a few regressions were identified which slowed things down.
we hope it will be soon.
