### ISSUE TITLE
Option for switch case indentation

### ISSUE THREAD

**Issue by andresgarza** [jshint/jshint#935]
It would be great to have an option to customize how switch statements should be indented (i.e. whether to follow Java's style of `case` statements having same indentation as `switch` or allowing extra indentation for `case` statements)

``` javascript
switch (condition) {
case ABC:
    statements;
    break;
case DEF:
    statements;
    break;
default:
    statements;
    break;
}
```

vs.

``` javascript
switch (condition) {
    case ABC:
        statements;
        break;
    case DEF:
        statements;
        break;
    default:
        statements;
        break;
}
```

**Comment by rogerioadris** [comment]
+1

**Comment by janborchers** [comment]
+1

**Comment by janeluck** [comment]
+1

**Comment by Again** [comment]
+1

**Comment by nicolo-ribaudo** [comment]
Style options will be removed in JSHint 3, you should consider using [jscs](http://jscs.info/)

**Comment by doberkofler** [comment]
i would recommend switching to eslint!

**Comment by baer** [comment]
I agree with eslint as well since you can enforce both style and linting rule and do so cleanly and separately at customizable warning levels. If you want some premade configs you can check out one of the many sharable config projects. Here's a shameless plug for the one I work on:

https://github.com/walmartlabs/eslint-config-defaults
