### ISSUE TITLE
Improve ASI support

### ISSUE THREAD

**Issue by valueof** [jshint/jshint#950]
Currently, the `asi` option in JSHint simply discards any warnings about missing semicolons. This leads to JSHint overlooking real bugs and generating false positives in some weird cases.
#### Examples

Example of a real bug that will be overlooked when `asi` option is turned on:

``` javascript
function test() {
  return
    { a: 1 }
}
```

Example of JSHint generating false positives:

``` javascript
var a = { b: 1 }
delete a.b
```
#### What needs to be done

JSHint should not generate any warnings about missing semicolon unless the new line is followed by the following symbols: `(`, `[`, `+`, `-`. In addition, JSHint should warn about `return` statements that are followed by a newlines that contain expressions that don't make sense on their own lines (like a string, or an object).

This bug consolidates #930 and #877.
#### There's bounty on this bug

You can get paid to fix this bug! See [our page on BountySource for more info](https://www.bountysource.com/#issues/127785-improve-asi-support).

**Comment by bob-eel** [comment]
(new here)
I'm using v2.6.3 with rhino, asi=true, and this kind of code doesn't wake jshint up:
<pre><code>
function a() {
	var b = 3 return 5
}
</code></pre>
in other terms, it looks like every single semicolon warning is being silenced; does jshint treat newlines as if they weren't there at all?

just like the purportedly fixed bug of above, my version doesn't always warn me correctly against this type of thing:
<pre><code>
var a = b
[3].foo() //nothing :(

var c = d
('a'+'b').foo() //nothing :(

var e = f
+g //Bad line breaking before '+'. ok

var h = i
-g //Bad line breaking before '-': ok

var j = k
/qwe/.foo() //Bad line breaking before '/'.
//yet it goes on ignoring the first / and "throws" an error telling me
//that '.foo' isn't the indentifier it expected; it however doesn't have any problem, first '/' excepted, with this type of thing:
var foo = bar
/aze/4
//is it its normal behavior?

</code></pre>
anyhow, quite annoying for someone who uses asi like me; quite absurd too that the two first asi exceptions (by far, more common than the three others) don't raise any warning :/

**Comment by guyzmo** [comment]
I do not understand what's your issue with:

```javascript
function a() {
    var b = 3 return 5
}
```

because it's just totally invalid, and won't compile anyway! But it does not look to me like a failure for asi, as I see no asi would happen here.

About the following miss:

```javascript
var a = b
[3].foo() ////nothing :(
```

you're right it might need to show off an error, as the code won't compile and is an obvious miss. Though, it should not be warning against asi there, but warning it because of the following example to consider:

```javascript
var i = 3;
var b = [];
var a = b[i] = [1];
```

vs

```javascript
var i = 3;
var b = [];
var a = b
[i] = [1];
```

both are legit JS, but the carriage return on second one could be an unwanted one, changing the semantics of the snipped.

The same logic applies to:

```javascript
var c = d
('a'+'b').foo()
```

versus 

```javascript
var c = d('a'+'b').foo()
```

All in all, it's better to warn too much about possible asi problems, and enforce the user to insert them wherever it could be a possible ambiguity.

Anyway, you shalln't rely on automagic semi-column insertion, but instead insert them to make your code as precise as possible, on then use that warning to get attention where there could be some errors. It's actually part of Crockford's *Javascript: The Good Parts* piece, which led to the writing of jslint, jshint ancestor ;-)

**Comment by guyzmo** [comment]
though because that issue has been closed a year and half, maybe shall we open a new issue to precise those scenarios?
